# Step 1: import npzfile and check info

In [2]:
import matplotlib.pyplot as plt
import numpy as np

npzfile = np.load('0602-mss-revisit-135-results.npz')
# npzfile = np.load('0509-com-444-results.npz')
# npzfile = np.load('0601-mms-48-results.npz')
# npzfile = np.load('0601-3_4_50cases-results.npz')
# npzfile = np.load('0509-low-com-210-results.npz')
# npzfile = np.load('0507-115-1-results.npz')
# npzfile = np.load('0508-low-1-results.npz')
# npzfile=np.load('0509-low-110-results.npz')
x, y1, y2, y3 = npzfile['alloc'], npzfile['rt_50'], npzfile['rt_99'], npzfile['rps']

In [57]:
# npzfile = np.load('0507-all-110-results.npz')
# x, y1, y2, y3 = npzfile['alloc'], npzfile['rt_50'], npzfile['rt_99'], npzfile['rps']
# npzfile = np.load('0508-low-105-results.npz')
# x_, y1_, y2_, y3_ = npzfile['alloc'], npzfile['rt_50'], npzfile['rt_99'], npzfile['rps']

# x__ = np.append(x, x_, axis=0)
# y1__ = np.append(y1, y1_, axis=0)
# y2__ = np.append(y2, y2_, axis=0)
# y3__ = np.append(y3, y3_, axis=0)

# np.savez('0508-com-215-results.npz',alloc=x__,rt_50=y1__, rt_99=y2__, rps=y3__)

In [3]:
len(x), len(y1), len(y2), len(y3)

(135, 135, 135, 135)

In [59]:

y1[0:10] # 50% response time
y2[0:10] # 99% response time
y3[0:10] # request per second
x[0:10] # allocation

array([[0., 2., 0., 0., 1., 0., 0., 0., 1.],
       [0., 1., 0., 3., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0., 2.],
       [0., 1., 0., 1., 0., 0., 0., 1., 5.],
       [0., 1., 0., 1., 0., 0., 0., 2., 4.],
       [0., 1., 0., 0., 0., 0., 3., 0., 0.],
       [0., 1., 0., 1., 0., 1., 1., 0., 0.],
       [0., 1., 0., 2., 1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 1., 0., 0., 1., 4.]])

55

In [84]:
retest=x[(x[:,3]!=0) + (x[:,4]!=0)]

In [103]:
# dataset_x_to_profile_setting(retest)

In [113]:
to_print_list=[]
# set(retest_setting)
for item in retest_setting:
  to_print=[str(j) for j in item[1:]]
  to_print_list.append('-'.join(to_print))

In [120]:
for item in set(to_print_list):
  print(item, end=' ')
print('\n',len(set(to_print_list)))

0-0-0-3-4-5-5 0-3-4-6-6-8-9 0-0-0-0-3-4-8 0-0-2-4-5-7-9 0-0-3-3-5-6-9 0-0-1-3-4-5-6 0-0-0-0-1-1-7 0-0-0-0-4-7-9 0-0-0-0-0-4-9 0-0-0-0-0-4-5 0-1-5-6-8-9-9 0-4-4-5-6-7-9 0-0-0-1-4-8-8 0-0-0-0-0-4-7 0-0-0-0-1-3-5 0-0-1-5-9-9-9 0-1-2-3-5-6-7 0-0-0-1-1-5-7 0-0-0-3-4-8-9 0-0-1-4-5-7-9 0-0-0-1-4-5-7 0-0-0-0-4-6-7 0-0-0-0-4-8-9 0-0-0-3-5-9-9 0-0-0-0-0-1-5 0-0-0-1-3-4-5 0-0-1-3-4-5-8 0-0-0-1-3-4-8 0-0-1-3-4-8-8 0-0-0-0-0-2-4 0-0-0-0-3-5-8 0-0-1-3-4-5-9 0-0-0-0-0-3-4 0-0-1-3-3-3-4 0-0-4-5-5-8-9 0-0-0-0-0-0-5 0-0-1-4-7-8-9 0-0-0-0-4-6-9 0-0-0-0-1-5-7 0-0-0-0-4-7-8 0-0-0-2-4-9-9 0-0-0-0-3-5-7 0-0-0-0-1-5-9 0-0-0-0-4-5-6 0-0-0-5-8-9-9 0-0-0-4-6-6-9 0-0-1-4-8-8-9 0-0-1-1-3-4-7 0-0-1-3-4-7-7 0-0-0-0-0-4-4 0-0-0-4-5-8-9 0-0-0-2-3-5-9 0-0-0-0-1-4-8 0-0-0-0-4-6-8 0-0-0-1-1-3-4 0-0-0-0-0-5-9 0-0-0-3-4-5-9 0-0-0-0-1-1-1 0-0-0-0-1-4-9 0-0-0-3-5-6-8 0-0-1-3-5-6-7 0-0-0-0-5-6-7 0-0-0-1-2-4-9 0-0-0-0-3-5-5 0-0-0-0-1-4-7 0-0-0-4-6-8-9 0-0-1-1-1-3-4 0-0-0-3-5-6-9 0-0-0-2-4-5-8 0-0-0-3-5-7-9 0-0-0-0-1-4-6 0-0-0-

In [121]:
fourty_eight_setting=['2-2-2-2-2-3-4','2-2-3-3-3-3-3','1-1-2-2-2-3-4','0-1-1-1-2-3-4','0-1-2-2-3-4-4','2-2-2-2-2-2-3','0-0-1-1-3-4-4','1-1-1-1-1-4-4','0-0-0-0-0-3-4','0-1-1-1-1-3-4','1-3-3-3-4-4-4','1-1-2-2-2-2-3','0-1-2-3-4-4-4','0-3-3-3-3-3-3','1-1-1-1-1-2-4','0-0-0-2-2-3-3','3-3-3-3-4-4-4','0-0-3-3-3-4-4','3-3-3-3-4-4-4','0-0-0-3-3-3-3','0-1-1-3-3-3-4','0-1-1-1-4-4-4','0-1-1-2-3-4-4','0-0-2-2-2-3-3','0-1-2-2-2-4-4','3-3-3-4-4-4-4','0-0-0-0-1-4-4','0-2-4-4-4-4-4','1-1-2-2-3-3-3','0-0-4-4-4-4-4','0-0-1-2-2-2-4','1-2-3-3-3-3-4','2-2-3-3-3-3-4','0-0-0-0-0-1-4','0-1-1-1-2-2-3','0-0-2-3-3-4-4','2-4-4-4-4-4-4','2-2-4-4-4-4-4','0-0-0-0-1-3-3','2-2-2-2-2-2-4','1-1-2-3-3-3-4','0-0-0-3-3-3-4','0-0-0-1-3-3-3','2-2-2-3-3-4-4','0-1-1-1-1-1-3','0-1-1-1-2-2-3','0-0-0-0-2-3-4','1-2-2-2-2-2-4','2-2-2-2-3-3-4','1-1-2-2-3-4-4']

In [125]:
for item in fourty_eight_setting:
  if item in to_print_list:
    print(item)

0-0-0-0-0-3-4
0-0-0-0-0-1-4


In [59]:
even_number = (np.sum(x, axis=1) % 2 == 0)
x[~even_number]

array([[1. , 1. , 1. , 1. , 0. , 0. , 0. , 3. , 0. ],
       [3. , 1. , 1. , 0. , 0. , 0. , 0. , 2. , 0. ],
       [5. , 1. , 0.5, 0.5, 0. , 0. , 0. , 0. , 0. ],
       [3. , 1. , 0.5, 0.5, 0. , 0. , 2. , 0. , 0. ]])

In [21]:
# if still exists odd x, remove them for all x, y1, y2, y3
even_number

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [22]:
even_number = (np.sum(x, axis=1) % 2 == 0)

In [23]:
len(x)

106

In [35]:
x

array([[2., 3., 3., 0., 0., 0., 0., 0., 0.],
       [0., 1., 4., 0., 0., 0., 0., 0., 0.],
       [1., 4., 0., 2., 0., 0., 0., 0., 0.],
       [3., 1., 0., 3., 0., 0., 0., 0., 0.],
       [2., 4., 1., 1., 0., 0., 0., 0., 0.],
       [0., 1., 3., 1., 0., 0., 0., 0., 0.],
       [0., 1., 3., 2., 0., 0., 0., 0., 0.],
       [0., 2., 8., 6., 0., 0., 0., 0., 0.],
       [0., 1., 0., 5., 0., 0., 0., 0., 0.],
       [1., 3., 1., 2., 0., 0., 0., 0., 0.],
       [0., 3., 0., 5., 0., 0., 0., 0., 0.],
       [0., 1., 3., 4., 0., 0., 0., 0., 0.],
       [0., 1., 6., 0., 0., 0., 0., 0., 0.],
       [2., 2., 1., 2., 0., 0., 0., 0., 0.],
       [0., 3., 4., 1., 0., 0., 0., 0., 0.],
       [2., 3., 1., 2., 0., 0., 0., 0., 0.],
       [0., 3., 5., 0., 0., 0., 0., 0., 0.],
       [2., 5., 1., 0., 0., 0., 0., 0., 0.],
       [2., 1., 1., 2., 0., 0., 0., 0., 0.],
       [2., 2., 3., 1., 0., 0., 0., 0., 0.],
       [2., 1., 3., 1., 0., 0., 0., 0., 0.],
       [1., 6., 0., 1., 0., 0., 0., 0., 0.],
       [0.

# Step 2: Checking which logs need fix

In [86]:
def dataset_x_to_profile_setting(array, verbose=True):
  # array = x[~even_number][:2] # shape: (2, 9)

  summary_setting = None
  for item in array:
    setting = [2] # the first 2 is necessary
    for i in range(len(item)):
      if item[i] != 0:
        repeat_time = int(round(item[i]/2 + 0.001)) # make 3/2 => 2
        if verbose and item[i] % 2 != 0:
          print("%s, %d: %.3f => %d; " % (item, i+1, item[i], repeat_time), end='')
        if i == 1: # i.e., minus 1 repeat_time for '2'
          repeat_time -= 1
        for num in range(repeat_time):
          setting.append(i+1)
    if len(setting) < 8: # not occupying all slots
      # workload specific: inserting "0" after the first "2".
      for i in range(8-len(setting)):
        setting.insert(1, 0)
    # end of setting building
    if verbose:
      print(setting)

    if summary_setting is None:
      summary_setting = [setting]
    else:
      summary_setting.append(setting)

  summary_setting.sort()
  if verbose:
    print(summary_setting)

  return summary_setting

  

In [13]:
summary_setting = dataset_x_to_profile_setting(x[~even_number])
summary_setting

[0. 2. 0. 2. 0. 0. 0. 1. 2.], 8: 1.000 => 1; [2, 0, 0, 0, 0, 4, 8, 9]
[0. 2. 0. 2. 0. 0. 0. 3. 0.], 8: 3.000 => 2; [2, 0, 0, 0, 0, 4, 8, 8]
[0. 4. 0. 0. 2. 0. 0. 1. 0.], 8: 1.000 => 1; [2, 0, 0, 0, 0, 2, 5, 8]
[0. 2. 3. 0. 0. 0. 0. 2. 0.], 3: 3.000 => 2; [2, 0, 0, 0, 0, 3, 3, 8]
[0. 2. 2. 0. 0. 0. 2. 1. 0.], 8: 1.000 => 1; [2, 0, 0, 0, 0, 3, 7, 8]
[0. 2. 0. 0. 2. 0. 0. 1. 2.], 8: 1.000 => 1; [2, 0, 0, 0, 0, 5, 8, 9]
[0. 4. 0. 2. 0. 0. 0. 1. 0.], 8: 1.000 => 1; [2, 0, 0, 0, 0, 2, 4, 8]
[0. 2. 0. 0. 0. 0. 2. 3. 0.], 8: 3.000 => 2; [2, 0, 0, 0, 0, 7, 8, 8]
[0. 2. 2. 0. 0. 2. 0. 1. 0.], 8: 1.000 => 1; [2, 0, 0, 0, 0, 3, 6, 8]
[0. 2. 1. 0. 0. 2. 0. 0. 2.], 3: 1.000 => 1; [2, 0, 0, 0, 0, 3, 6, 9]
[0. 2. 2. 0. 0. 0. 0. 3. 0.], 8: 3.000 => 2; [2, 0, 0, 0, 0, 3, 8, 8]
[0. 4. 0. 0. 0. 0. 0. 3. 0.], 8: 3.000 => 2; [2, 0, 0, 0, 0, 2, 8, 8]
[0. 2. 0. 0. 0. 2. 2. 1. 0.], 8: 1.000 => 1; [2, 0, 0, 0, 0, 6, 7, 8]
[0. 2. 3. 0. 2. 0. 0. 0. 0.], 3: 3.000 => 2; [2, 0, 0, 0, 0, 3, 3, 5]
[0. 2. 0. 2. 0. 2. 0

[[2, 0, 0, 0, 0, 2, 4, 8],
 [2, 0, 0, 0, 0, 2, 5, 8],
 [2, 0, 0, 0, 0, 2, 8, 8],
 [2, 0, 0, 0, 0, 3, 3, 5],
 [2, 0, 0, 0, 0, 3, 3, 8],
 [2, 0, 0, 0, 0, 3, 6, 8],
 [2, 0, 0, 0, 0, 3, 6, 9],
 [2, 0, 0, 0, 0, 3, 7, 8],
 [2, 0, 0, 0, 0, 3, 8, 8],
 [2, 0, 0, 0, 0, 4, 4, 8],
 [2, 0, 0, 0, 0, 4, 6, 8],
 [2, 0, 0, 0, 0, 4, 8, 8],
 [2, 0, 0, 0, 0, 4, 8, 9],
 [2, 0, 0, 0, 0, 5, 8, 9],
 [2, 0, 0, 0, 0, 6, 7, 8],
 [2, 0, 0, 0, 0, 7, 8, 8]]

1. Run pyscript_1 to the fix-log

2. Copy these .csv files to summary folder.

3. Rerun pyscript_2 and _3 to collect new .npz

4. Import new .npz into this notebook again.

# Step 3: After fix, still wrong, please remove them

In [44]:
def remove_odd_records(x, y1, y2, y3):
  even_number = (np.sum(x, axis=1) % 2 == 0)
  indices = np.where(~even_number)
  x = np.delete(x, indices, 0)
  y1 = np.delete(y1, indices, 0)
  y2 = np.delete(y2, indices, 0)
  y3 = np.delete(y3, indices, 0)
  return x, y1, y2, y3

In [45]:
x,y1,y2,y3=remove_odd_records(x, y1, y2, y3)

And save to new .npz file

In [36]:
# np.savez('0507-115-1-results.npz',alloc=x,rt_50=y1, rt_99=y2, rps=y3)
# np.savez('0508-low-1-results.npz',alloc=x,rt_50=y1, rt_99=y2, rps=y3)
# np.savez('0508-low-110-results.npz',alloc=x,rt_50=y1, rt_99=y2, rps=y3)
# np.savez('dataset-0423x2-0424x2-0425x2-median.npz',alloc=x,rt_50=y1, rt_99=y2, rps=y3)
np.savez('0601-mms-48-results.npz',alloc=x,rt_50=y1, rt_99=y2, rps=y3)


# Step 4: Combine different npz files into one

In [60]:
one = '0509-com-325-results.npz'
two = 'dataset-0423x2-0424x2-0425x2-median.npz'

npzfile = np.load(one)
x_one, y1_one, y2_one, y3_one = npzfile['alloc'], npzfile['rt_50'], npzfile['rt_99'], npzfile['rps']

npzfile = np.load(two)
x_two, y1_two, y2_two, y3_two = npzfile['alloc'], npzfile['rt_50'], npzfile['rt_99'], npzfile['rps']

x_com = np.append(x_one, x_two, axis=0)
y1_com = np.append(y1_one, y1_two, axis=0)
y2_com = np.append(y2_one, y2_two, axis=0)
y3_com = np.append(y3_one, y3_two, axis=0)

In [61]:
len(x_com),len(y1_com),len(y2_com),len(y3_com)

(444, 444, 444, 444)

In [62]:
com = '0509-com-444-results.npz'

In [63]:
np.savez(com,alloc=x_com,rt_50=y1_com, rt_99=y2_com, rps=y3_com)

# Fix non-even problem

In [53]:
npzfile_path_list = ['dataset-0423x2-0424x2-0425x2-median.npz']

In [54]:
for one in npzfile_path_list:
  npzfile = np.load(one)
  x, y1, y2, y3 = npzfile['alloc'], npzfile['rt_50'], npzfile['rt_99'], npzfile['rps']
  x = x / 2
  np.savez(one, alloc=x ,rt_50=y1, rt_99=y2, rps=y3)