In [6]:
npzfile = np.load('../datasets/0627-8slot-503.npz')
alloc, rt_50, rt_99, rps=npzfile['alloc'], npzfile['rt_50'], npzfile['rt_99'], npzfile['rps']
alloc_list = alloc.tolist()

In [36]:
alloc[35], rps[35]

(array([0., 2., 1., 1., 1., 2., 0., 0., 1.]),
 array([nan, 0.98, 1.73, 6.29, 2.32, 0.955, nan, nan, 1.84], dtype=object))

In [32]:
for index in range(len(alloc_list)):
    print(index, alloc_list[index])

0 [0.0, 0.0, 1.0, 2.0, 1.0, 2.0, 0.0, 1.0, 0.0]
1 [1.0, 0.0, 1.0, 1.0, 1.0, 2.0, 1.0, 1.0, 0.0]
2 [1.0, 0.0, 1.0, 4.0, 0.0, 0.0, 0.0, 0.0, 0.0]
3 [2.0, 0.0, 1.0, 3.0, 0.0, 0.0, 1.0, 0.0, 0.0]
4 [0.0, 0.0, 4.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0]
5 [0.0, 0.0, 4.0, 1.0, 1.0, 0.0, 0.0, 0.0, 2.0]
6 [0.0, 0.0, 2.0, 1.0, 0.0, 2.0, 0.0, 3.0, 0.0]
7 [3.0, 0.0, 2.0, 1.0, 0.0, 0.0, 2.0, 0.0, 0.0]
8 [0.0, 0.0, 3.0, 4.0, 0.0, 0.0, 0.0, 0.0, 0.0]
9 [0.0, 0.0, 1.0, 2.0, 1.0, 0.0, 3.0, 0.0, 1.0]
10 [0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 2.0]
11 [1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 3.0, 1.0, 1.0]
12 [0.0, 1.0, 1.0, 2.0, 0.0, 1.0, 3.0, 0.0, 0.0]
13 [0.0, 0.0, 1.0, 3.0, 1.0, 1.0, 1.0, 1.0, 0.0]
14 [0.0, 0.0, 1.0, 1.0, 2.0, 0.0, 2.0, 0.0, 2.0]
15 [0.0, 1.0, 2.0, 1.0, 0.0, 2.0, 1.0, 0.0, 0.0]
16 [1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 2.0, 1.0]
17 [0.0, 0.0, 1.0, 2.0, 1.0, 0.0, 1.0, 2.0, 1.0]
18 [1.0, 0.0, 2.0, 2.0, 0.0, 0.0, 1.0, 0.0, 0.0]
19 [1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 3.0, 1.0, 0.0]
20 [1.0, 0.0, 2.0, 2.0, 1.0, 0

In [22]:
def reproduce_x_to_profile_setting_list(self, array):  # 0627
    # input: array, shape: (2, 9), e.g., [[2. 1. 0. 4. 0. 1. 0. 0. 0.]]
    # output: [[1, 1, 2, 4, 4, 4, 4, 6]]
    summary_setting_list = None
    setting = []
    for item in array:
        for i in range(len(item)):
            if item[i] != 0:
                for num in range(int(item[i])):
                    setting.append(i+1)

        if len(setting) > 8: # over allocated
            print("[ERROR]: Too many containers: ", item)
        else:
            for i in range(8-len(setting)):
                setting.insert(0, 0) # add 0 in the first place

        # now the setting is well sorted
        if summary_setting_list is None:
          summary_setting_list = [setting]
        else:
          summary_setting_list.append(setting)

    return summary_setting_list

In [25]:
input_a=reproduce_x_to_profile_setting_list(_,  np.array([[1.0, 0.0, 2.0, 3.0, 0.0, 0.0, 0.0, 0.0, 0.0]]));
input_a

[[0, 0, 1, 3, 3, 4, 4, 4]]

In [30]:
'-'.join([str(i) for i in input_a[0]])

'0-0-1-3-3-4-4-4'

In [3]:
import numpy as np

In [105]:
item_1=np.array([1,1,2,1,0,0,1,2,0],dtype=int)
item_1=np.array([0, 1, 0, 0, 2, 0, 0, 0, 1])
# item_1=np.array([1.,1.,2.,0.,0.,4.,0.,0.,0.], dtype=int)
item_1  # Luping's input: 9: R1 R2 M1 M2 + 5

array([0, 1, 0, 0, 2, 0, 0, 0, 1])

In [106]:
item_2=r1r2m1m2_to_mms_local_remote_1d(item_1); item_2  # 9: CPU, Redis, MMS_L, MMS_R + 5

array([0, 1, 0, 0, 2, 0, 0, 0, 1])

In [107]:
item_3=reproduce_x_to_profile_setting([item_2])[0]; item_3  # 8 loc: [] [] [] []

[2, 0, 0, 0, 0, 5, 5, 9]

In [114]:
def eight_to_nine(in_array):
    out_array = np.array([0]*9)
    for item in in_array:
        if item != 0:
            out_array[int(item-1)]+=1
    return out_array

In [115]:
item_4=eight_to_nine(item_3); item_4 # alloc_match

array([0, 1, 0, 0, 2, 0, 0, 0, 1])

In [116]:
total_rps = 0
try:
    index = alloc_list.index(item_4.tolist())
# rps_breakdown = rps[index]
# rps_sum = [ r * n for (r, n) in zip(rps_breakdown, query_allocation_array)]
# rps_sum = sum(np.nan_to_num(np.array(rps_sum)))
# total_rps += rps_sum
    rps_breakdown = rps[index]
    rps_sum = [ r * n for (r, n) in zip(rps_breakdown, item_4)]
    rps_sum = sum(np.nan_to_num(np.array(rps_sum)))
    total_rps += rps_sum
    print("luping:", item_1)
    print(" query:", item_4)
    print("[rps/container]:", rps_breakdown)
except ValueError:
    print("Not Found:", item_4, " (from)", item_1)

luping: [0 1 0 0 2 0 0 0 1]
 query: [0 1 0 0 2 0 0 0 1]
[rps/container]: [nan 1.24 nan nan 2.98 nan nan nan 2.11]


In [117]:
mms_local_remote_to_r1r2m1m2_1d(item_1, rps_breakdown)

array([0, 1.24, 0, 0, 2.98, nan, nan, nan, 2.11], dtype=object)

In [222]:
query_results_r1r2m1m2('results-sim-spare8081.npz', ar_sim_in[0], debug=True)

[DEBUG]   luping: [0, 1, 0, 0, 2, 0, 0, 0, 1]
[DEBUG]    query: [0 1 0 0 2 0 0 0 1]
[DEBUG] temp rps: [nan 1.24 nan nan 2.98 nan nan nan 2.11]
[0, 1, 0, 0, 2, 0, 0, 0, 1] throughput: 9.3100
	[rps/cntr] [0 1.24 0 0 2.98 nan nan nan 2.11]
[DEBUG]   luping: [0, 1, 0, 0, 0, 0, 2, 0, 1]
[DEBUG]    query: [0 1 0 0 0 0 2 0 1]
[DEBUG] temp rps: [nan 1.24 nan nan nan nan 0.625 nan 2.12]
[0, 1, 0, 0, 0, 0, 2, 0, 1] throughput: 4.6100
	[rps/cntr] [0 1.24 0 0 nan nan 0.625 nan 2.12]
[DEBUG]   luping: [0, 1, 0, 0, 0, 0, 0, 0, 1]
[DEBUG]    query: [0 1 0 0 0 0 0 0 1]
Not Found: [0 1 0 0 0 0 0 0 1]  (from) [0, 1, 0, 0, 0, 0, 0, 0, 1]
[DEBUG]   luping: [0, 1, 0, 0, 0, 0, 0, 0, 1]
[DEBUG]    query: [0 1 0 0 0 0 0 0 1]
Not Found: [0 1 0 0 0 0 0 0 1]  (from) [0, 1, 0, 0, 0, 0, 0, 0, 1]
[DEBUG]   luping: [1, 1, 2, 0, 0, 4, 0, 0, 0]
[DEBUG]    query: [0 2 2 0 0 4 0 0 0]
Not Found: [0 2 2 0 0 4 0 0 0]  (from) [1, 1, 2, 0, 0, 4, 0, 0, 0]
[DEBUG]   luping: [1, 1, 2, 1, 0, 0, 1, 2, 0]
[DEBUG]    query: [0 2 3 

In [221]:
query_results_r1r2m1m2('results-sim-spare8081.npz', [[1,1,2,0,0,4,0,0,0]], debug=True)

[DEBUG]   luping: [1, 1, 2, 0, 0, 4, 0, 0, 0]
[DEBUG]    query: [0 2 2 0 0 4 0 0 0]
Not Found: [0 2 2 0 0 4 0 0 0]  (from) [1, 1, 2, 0, 0, 4, 0, 0, 0]
Total Throughput: 0.0000


In [223]:
reproduce_x_to_profile_setting([[0, 2, 2, 0, 0, 4, 0, 0, 0]], r1r2m1m2=True)

[[2, 2, 4, 4, 6, 6, 6, 6]]

In [220]:
def query_results_r1r2m1m2(npz_file_path, query_allocation_array_list, debug=False):
    npzfile = np.load(npz_file_path)
    alloc, rt_50, rt_99, rps=npzfile['alloc'], npzfile['rt_50'], npzfile['rt_99'], npzfile['rps']
    alloc_list = alloc.tolist()

    total_rps = 0
    for item_1 in query_allocation_array_list:
        item_2=r1r2m1m2_to_mms_local_remote_1d(item_1); # 9: CPU, Redis, MMS_L, MMS_R + 5
        item_3=reproduce_x_to_profile_setting([item_2])[0]; # 8 loc: [] [] [] []

        def eight_to_nine(in_array):
            out_array = np.array([0]*9)
            for item in in_array:
                if item != 0:
                    out_array[int(item-1)]+=1
            return out_array

        item_4=eight_to_nine(item_3); # alloc_match
        
        if debug:
            print("[DEBUG]   luping:", item_1)
            print("[DEBUG]    query:", item_4)
            
        try:
            index = alloc_list.index(item_4.tolist())
            temp_rps_breakdown = rps[index]

            if debug:
                print("[DEBUG] temp rps:", np.nan_to_num(temp_rps_breakdown))

            rps_breakdown = mms_local_remote_to_r1r2m1m2_1d(item_1, np.nan_to_num(temp_rps_breakdown))
            rps_sum = [ r * n for (r, n) in zip(rps_breakdown, item_1)]
            rps_sum = sum(np.nan_to_num(np.array(rps_sum)))
            total_rps += rps_sum

            print("%s throughput: %.4f" % (item_1, rps_sum))
            print("\t[rps/cntr] %s" % rps_breakdown)
        except ValueError:
            print("Not Found:", item_4, " (from)", item_1)
    print("Total Throughput: %.4f" % total_rps)

In [170]:
for i in range(5):
    print('--------',i+1,'--------')
    query_results_r1r2m1m2('results-sim-spare8081.npz', ar_sim_in[i])

-------- 1 --------
[0, 1, 0, 0, 2, 0, 0, 0, 1] throughput: 9.3100
	[rps/cntr] [0 1.24 0 0 2.98 nan nan nan 2.11]
[0, 1, 0, 0, 0, 0, 2, 0, 1] throughput: 4.6100
	[rps/cntr] [0 1.24 0 0 nan nan 0.625 nan 2.12]
Not Found: [0 1 0 0 0 0 0 0 1]  (from) [0, 1, 0, 0, 0, 0, 0, 0, 1]
Not Found: [0 1 0 0 0 0 0 0 1]  (from) [0, 1, 0, 0, 0, 0, 0, 0, 1]
Not Found: [0 2 2 0 0 4 0 0 0]  (from) [1, 1, 2, 0, 0, 4, 0, 0, 0]
[1, 1, 2, 1, 0, 0, 1, 2, 0] throughput: 13.7850
	[rps/cntr] [0.955 0.955 3.375 3.375 nan nan 0.46 0.645 nan]
[0, 1, 0, 0, 0, 0, 0, 0, 0] throughput: 1.2450
	[rps/cntr] [0 1.245 0 0 nan nan nan nan nan]
[1, 1, 0, 3, 0, 0, 1, 2, 0] throughput: 13.7850
	[rps/cntr] [0.955 0.955 0 3.375 nan nan 0.46 0.645 nan]
[1, 5, 0, 0, 2, 0, 0, 0, 0] throughput: 10.2300
	[rps/cntr] [0.925 0.925 0 0 2.34 nan nan nan nan]
Total Throughput: 52.9650
-------- 2 --------
[1, 1, 1, 0, 1, 0, 1, 0, 0] throughput: 9.6800
	[rps/cntr] [0.93 0.93 4.27 0 2.93 nan 0.62 nan nan]
[1, 1, 1, 0, 1, 0, 0, 1, 0] throughput

In [189]:
alloc_list

[[0.0, 1.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0],
 [0.0, 2.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 3.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0],
 [0.0, 2.0, 1.0, 0.0, 3.0, 1.0, 1.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.0, 0.0],
 [0.0, 2.0, 3.0, 0.0, 0.0, 0.0, 1.0, 2.0, 0.0],
 [0.0, 2.0, 3.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0],
 [0.0, 2.0, 1.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0],
 [0.0, 2.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 5.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 2.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 2.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 2.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 4.0, 0.0, 0.0, 0.0],
 [0.0, 2.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 3.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 4.0, 0.0, 0.0],
 [0.0, 2.0, 0.0, 1.0, 0.0, 0.0, 2.0, 1.0, 1.0],
 [0.0, 2.0, 1.0, 0.0, 2.0, 0.0, 1.0, 0.0

In [194]:
def reproduce_x_to_profile_setting(array, r1r2m1m2=False, with_redis=True, verbose=True):
  # date: 2019-0617
  # input: array, shape: (2, 9), e.g., [[2. 1. 0. 4. 0. 1. 0. 0. 0.]]
  # output: [[2, 1, 1, 4, 4, 4, 4, 6]]
    summary_setting = None
    for item in array:
        if r1r2m1m2:
            item=r1r2m1m2_to_mms_local_remote_1d(item); # 9: CPU, Redis, MMS_L, MMS_R + 5

        if with_redis:
            setting = [2]
            item[1] -= 1 # put 1 Redis at top
        else:
            setting = []
        
        for i in range(len(item)):
            if item[i] != 0:
                for num in range(item[i]):
                    setting.append(i+1)

        if len(setting) > 8: # over allocated
            print("[ERROR]: Too many containers: ", item)
        else:
            for i in range(8-len(setting)):
                setting.insert(1, 0) # add 0 after the first place

        if summary_setting is None:
          summary_setting = [setting]
        else:
          summary_setting.append(setting)

    return summary_setting


def mms_local_remote_to_r1r2m1m2_1d(input_x, input_y):
    """
    input_x  = [1, 0, 1, 0, 1, 1, 0, 1, 3] # R1, R2, M1, M2, XXXXX
    output_x = [0, 1, 1, 0, 1, 1, 0, 1, 3] # CPU, Redis, MMS_LOCAL, MMS_REMOTE, XXXXX

    input_y  = [0.0000, 0.8218, 4.0633, 0.0000, 2.6703, 1.0034, 0.0000, 0.8029, 0.5026] # CPU, Redis, MMS_LOCAL, MMS_REMOTE, XXXXX
    output_y = [0.8218, 0.0000, 4.0633, 0.0000, 2.6703, 1.0034, 0.0000, 0.8029, 0.5026] # R1, R2, M1, M2, XXXXX
    """
    output_y = input_y.copy()  # input_y[-5:] unchanged

    if input_x[0] >= 1:  # if R1 exists
        output_y[0] = input_y[1]  # R1 = Redis
        if input_x[2] >= 1:  # if R1 & M1 co-exists
            output_y[2] = input_y[2]  # M1 = MMS_LOCAL
        else:
            output_y[2] = 0  # M1 = 0
    else:  # if R1 not exists
        output_y[0] = 0  # R1 = 0
        if input_x[2] >= 1:  # if M1 exists
            output_y[2] = input_y[3]  # M1 = MMS_REMOTE
        else:
            output_y[2] = 0  # M1 = 0

    if input_x[1] >= 1:  # if R2 exists
        output_y[1] = input_y[1]  # R2 = Redis
        if input_x[3] >= 1:  # if R2 & M2 co-exists
            output_y[3] = input_y[2]  # M1 = MMS_LOCAL
        else:
            output_y[3] = 0  # M2 = 0
    else:  # if R2 not exists
        output_y[1] = 0  # R1 = 0
        if input_x[3] >= 1:  # if M2 exists
            output_y[3] = input_y[3]  # M2 = MMS_REMOTE
        else:
            output_y[3] = 0  # M1 = 0

    return output_y


def r1r2m1m2_to_mms_local_remote_1d(input_x):
    """
    input_x  = [1, 0, 1, 0, 1, 1, 0, 1, 3] # R1, R2, M1, M2, XXXXX
    output_x = [0, 1, 1, 0, 1, 1, 0, 1, 3] # CPU, Redis, MMS_LOCAL, MMS_REMOTE, XXXXX
    """
    output_x = input_x.copy()  # input_x[-5:] unchanged

    num_redis = input_x[0] + input_x[1]  # Redis = R1 + R2
    num_mms_local = 0
    num_mms_remote = 0

    if input_x[0] >= 1:  # if R1 exists
        num_mms_local += input_x[2]  # MMS_LOCAL += R1
    else:
        num_mms_remote += input_x[2]  # MMS_REMOTE += R1

    if input_x[1] >= 1:  # if R2 exists
        num_mms_local += input_x[3]  # MMS_LOCAL += R2
    else:
        num_mms_remote += input_x[3]  # MMS_REMOTE += R2

    output_x[0] = 0  # Sysbench CPU records discarded
    output_x[1] = num_redis
    output_x[2] = num_mms_local
    output_x[3] = num_mms_remote

    return output_x

In [178]:
alloc

array([[ 0.,  1.,  2.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  2.,  0.,  0.,  0.,  0.,  0.,  0.,  2.],
       [ 0.,  2.,  0.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 0.,  3.,  1.,  0.,  0.,  1.,  1.,  1.,  0.],
       [ 0.,  2.,  1.,  0.,  3.,  1.,  1.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  4.,  0.],
       [ 0.,  4.,  6.,  0.,  0.,  0.,  2.,  4.,  0.],
       [ 0.,  2.,  3.,  0.,  0.,  1.,  0.,  0.,  1.],
       [ 0.,  2.,  1.,  0.,  0.,  0.,  0.,  2.,  0.],
       [ 0.,  2.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  1.,  1.,  0.,  1.,  0.,  1.],
       [ 0., 10.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  2.,  1.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  2.,  0.,  0.,  0.,  2.,  0.,  0.,  2.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  4.],
       [ 0.,  1.,  0.,  0.,  0.,  4.,  0.,  0.,  0.],
       [ 0.,  2.,  1.,  0.,  1.,  0.,  1.,  0.,  0.],
       [ 0.,  3.,  0.,  0.,  1.,  0.,  1.,  0.,  0.],
       [ 0.,  1.,  0.,  0., 

In [97]:
def query_results(npz_file_path, query_allocation_array_list):
    npzfile = np.load(npz_file_path)
    alloc, rt_50, rt_99, rps=npzfile['alloc'], npzfile['rt_50'], npzfile['rt_99'], npzfile['rps']
    alloc_list = alloc.tolist()

    total_rps = 0
    for query_allocation_array in query_allocation_array_list:
        try:
#             query_allocation_array = reproduce_x_to_profile_setting([query_allocation_array])[0]
            index = alloc_list.index(query_allocation_array)
            rps_breakdown = rps[index]
            rps_sum = [ r * n for (r, n) in zip(rps_breakdown, query_allocation_array)]
            rps_sum = sum(np.nan_to_num(np.array(rps_sum)))
            total_rps += rps_sum
            print("%s throughput: %.4f" % (query_allocation_array, rps_sum))
            print("\t[rps/cntr] %s" % rps_breakdown)
        except ValueError:
            print("%s throughput: nan" % (query_allocation_array))
            print("\t xxxxx [NOT FOUND] xxxxx")
            rps_breakdown = [np.nan] * 9
            rps_sum = np.nan
    print("Total Throughput: %.4f" % total_rps)


In [101]:
ar_444_in = [[[2, 1, 0, 4, 0, 1, 0, 0, 0],[1, 1, 0, 0, 0, 3, 0, 3, 0],[0, 2, 0, 0, 0, 0, 2, 1, 0],[1, 1, 0, 0, 0, 0, 0, 0, 1],[0, 1, 1, 0, 2, 0, 1, 0, 0],[0, 1, 1, 0, 2, 0, 1, 0, 0],[0, 2, 0, 0, 0, 0, 0, 0, 1],[0, 1, 2, 0, 0, 0, 0, 0, 1],[0, 3, 0, 0, 0, 0, 0, 0, 1]],[[1, 1, 1, 0, 1, 0, 1, 0, 0],[1, 1, 1, 0, 1, 0, 0, 1, 0],[1, 1, 1, 0, 0, 1, 0, 1, 0],[1, 1, 0, 1, 0, 1, 0, 1, 0],[0, 2, 0, 1, 0, 1, 0, 1, 0],[0, 2, 0, 1, 0, 1, 0, 0, 1],[0, 2, 0, 1, 0, 0, 1, 0, 1],[0, 2, 0, 0, 1, 0, 1, 0, 1],[0, 1, 1, 0, 1, 0, 1, 0, 1]],[[4, 1, 0, 0, 0, 0, 0, 0, 0],[0, 5, 0, 0, 0, 0, 0, 0, 0],[0, 1, 4, 0, 0, 0, 0, 0, 0],[0, 1, 0, 4, 0, 0, 0, 0, 0],[0, 1, 0, 0, 4, 0, 0, 0, 0],[0, 1, 0, 0, 0, 4, 0, 0, 0],[0, 1, 0, 0, 0, 0, 4, 0, 0],[0, 1, 0, 0, 0, 0, 0, 4, 0],[0, 1, 0, 0, 0, 0, 0, 0, 4]],[[1, 1, 1, 0, 0, 0, 0, 2, 0],[0, 2, 0, 1, 2, 0, 1, 0, 0],[2, 1, 0, 0, 1, 0, 1, 0, 0],[0, 2, 1, 0, 0, 0, 2, 1, 1],[0, 2, 0, 2, 0, 2, 0, 0, 1],[0, 1, 0, 0, 0, 1, 0, 0, 1],[1, 1, 0, 0, 0, 0, 0, 0, 0],[0, 1, 2, 0, 1, 1, 0, 0, 1],[0, 2, 0, 1, 0, 0, 0, 1, 0]],[[2, 1, 1, 0, 0, 1, 1, 1, 0],[0, 1, 0, 1, 0, 0, 1, 0, 0],[0, 1, 0, 0, 0, 0, 0, 2, 0],[0, 1, 0, 0, 0, 1, 0, 0, 1],[1, 1, 2, 1, 0, 1, 0, 0, 1],[0, 3, 0, 0, 0, 0, 1, 1, 0],[1, 1, 0, 0, 0, 0, 0, 0, 2],[0, 2, 1, 1, 1, 0, 0, 0, 0],[0, 2, 0, 1, 3, 1, 1, 0, 0]]]

ar_sim_in=[[[0,1,0,0,2,0,0,0,1],[0,1,0,0,0,0,2,0,1],[0,1,0,0,0,0,0,0,1],[0,1,0,0,0,0,0,0,1],[1,1,2,0,0,4,0,0,0],[1,1,2,1,0,0,1,2,0],[0,1,0,0,0,0,0,0,0],[1,1,0,3,0,0,1,2,0],[1,5,0,0,2,0,0,0,0]],[[1,1,1,0,1,0,1,0,0],[1,1,1,0,1,0,0,1,0],[1,1,1,0,0,1,0,1,0],[1,1,0,1,0,1,0,1,0],[0,2,0,1,0,1,0,1,0],[0,2,0,1,0,1,0,0,1],[0,2,0,1,0,0,1,0,1],[0,2,0,0,1,0,1,0,1],[0,1,1,0,1,0,1,0,1]],[[4,1,0,0,0,0,0,0,0],[0,5,0,0,0,0,0,0,0],[0,1,4,0,0,0,0,0,0],[0,1,0,4,0,0,0,0,0],[0,1,0,0,4,0,0,0,0],[0,1,0,0,0,4,0,0,0],[0,1,0,0,0,0,4,0,0],[0,1,0,0,0,0,0,4,0],[0,1,0,0,0,0,0,0,4]],[[1,1,1,0,0,0,0,2,0],[0,2,0,1,2,0,1,0,0],[2,1,0,0,1,0,1,0,0],[0,2,1,0,0,0,2,1,1],[0,2,0,2,0,2,0,0,1],[0,1,0,0,0,1,0,0,1],[1,1,0,0,0,0,0,0,0],[0,1,2,0,1,1,0,0,1],[0,2,0,1,0,0,0,1,0]],[[2,1,1,0,0,1,1,1,0],[0,1,0,1,0,0,1,0,0],[0,1,0,0,0,0,0,2,0],[0,1,0,0,0,1,0,0,1],[1,1,2,1,0,1,0,0,1],[0,3,0,0,0,0,1,1,0],[1,1,0,0,0,0,0,0,2],[0,2,1,1,1,0,0,0,0],[0,2,0,1,3,1,1,0,0]]]

npzfile_444='results-444.npz'
npzfile_sim='results-sim.npz'

In [99]:
for i in range(5):
    print('--------',i+1,'--------')
    query_results(npzfile_444, ar_444_in[i])

-------- 1 --------
[2, 1, 0, 4, 0, 1, 0, 0, 0] throughput: 16.5650
	[rps/cntr] [1.585 1.0 nan 2.755 nan 1.375 nan nan nan]
[1, 1, 0, 0, 0, 3, 0, 3, 0] throughput: 6.6500
	[rps/cntr] [1.455 0.98 nan nan nan 0.635 nan 0.77 nan]
[0, 2, 0, 0, 0, 0, 2, 1, 0] throughput: 3.9100
	[rps/cntr] [nan 0.92 nan nan nan nan 0.625 0.82 nan]
[1, 1, 0, 0, 0, 0, 0, 0, 1] throughput: 5.0800
	[rps/cntr] [2.07 1.185 nan nan nan nan nan nan 1.825]
[0, 1, 1, 0, 2, 0, 1, 0, 0] throughput: 10.1250
	[rps/cntr] [nan 1.025 2.575 nan 2.95 nan 0.625 nan nan]
[0, 1, 1, 0, 2, 0, 1, 0, 0] throughput: 10.1250
	[rps/cntr] [nan 1.025 2.575 nan 2.95 nan 0.625 nan nan]
[0, 2, 0, 0, 0, 0, 0, 0, 1] throughput: 4.6100
	[rps/cntr] [nan 1.18 nan nan nan nan nan nan 2.25]
[0, 1, 2, 0, 0, 0, 0, 0, 1] throughput: 10.6550
	[rps/cntr] [nan 1.205 3.615 nan nan nan nan nan 2.22]
[0, 3, 0, 0, 0, 0, 0, 0, 1] throughput: 5.7850
	[rps/cntr] [nan 1.19 nan nan nan nan nan nan 2.215]
Total Throughput: 73.5050
-------- 2 --------
[1, 1, 1, 0,

In [130]:
from pyscript_utils import reproduce_x_to_profile_setting

In [154]:
# query = [0, 1, 0, 0, 0, 0, 0, 0, 1]
query = [0, 2, 2, 0, 0, 4, 0, 0, 0]

In [155]:
query_input = reproduce_x_to_profile_setting([query])
query_input

[[2, 2, 3, 3, 6, 6, 6, 6]]

In [156]:
filename = str(query_input[0]).replace(', ', '-')[1:-1]
filename = 'results/'+filename+'.csv'
filename

'results/2-2-3-3-6-6-6-6.csv'

In [157]:
import pandas as pd
src=pd.read_csv(filename)
src

App  Port   Name  # requests   50%   66%   75%   80%   90%  \
0                Redis  8081  Total         456  4800  4800  4900  4900  5000   
1                Redis  8082  Total         710  2900  3000  3100  3100  3200   
2   MXNet-ResNet-Local  8083  Total        2567   420   510   570   600   670   
3   MXNet-ResNet-Local  8084  Total        2621   390   490   550   580   660   
4           SYS-FILEIO  8085  Total         287  8000  8100  8200  8200  8300   
5           SYS-FILEIO  8086  Total         287  8000  8100  8200  8200  8300   
6           SYS-FILEIO  8087  Total         293  8000  8200  8200  8300  8400   
7           SYS-FILEIO  8088  Total         285  8100  8200  8200  8300  8400   
8                Redis  8081  Total         473  4600  4700  4700  4700  4800   
9                Redis  8082  Total         702  2900  3000  3100  3100  3200   
10  MXNet-ResNet-Local  8083  Total        2615   390   490   540   570   660   
11  MXNet-ResNet-Local  8084  Total        2672   380   480   530   560   650   
12          SYS-FILEIO  8085  Total         287  8000  8100  8200  8200  8300   
13          SYS-FILEIO  8086  Total         285  8000  8100  8200  8200  8300   

     95%     ...      Method  Name.1  # requests.1 # failures  \
0   5000     ...        None   Total           456          0   
1   3300     ...        None   Total           710          0   
2    760     ...        None   Total          2567          0   
3    750     ...        None   Total          2621          0   
4   8300     ...        None   Total           287          0   
5   8400     ...        None   Total           287          0   
6   8500     ...        None   Total           293          0   
7   8400     ...        None   Total           285          0   
8   4800     ...        None   Total           473          0   
9   3300     ...        None   Total           702          0   
10   730     ...        None   Total          2615          0   
11   720     ...        None   Total          2672          0   
12  8300     ...        None   Total           287          0   
13  8400     ...        None   Total           285          0   

   Median response time  Average response time  Min response time  \
0                  4800                   4734               3870   
1                  2900                   2864               2158   
2                   420                    432                184   
3                   390                    414                184   
4                  8000                   7823               6126   
5                  8000                   7819               6269   
6                  8000                   7667               4978   
7                  8100                   7884               6089   
8                  4600                   4576               3849   
9                  2900                   2894               2192   
10                  390                    411                177   
11                  380                    402                177   
12                 8000                   7808               6281   
13                 8000                   7865               5919   

    Max response time  Average Content Size  Requests/s  
0                5181                    68        0.77  
1                3537                    68        1.19  
2                1328                   576        4.28  
3                1301                   578        4.37  
4                8542                    98        0.48  
5                8487                    98        0.48  
6                8592                    98        0.49  
7                8461                    98        0.48  
8                4983                    68        0.79  
9                3503                    68        1.17  
10               1221                   578        4.36  
11               1244                   578        4.46  
12               8442                

In [158]:
WORKLOAD = ["SYS-CPU", "Redis", "MXNet-ResNet-Local", "MXNet-ResNet-Remote", "SYS-MEM", "SYS-FILEIO", "Stress-CPU", "Stress-MEM", "Stress-FILE"]
output_array = np.array([np.nan]*9)
for worki in range(len(WORKLOAD)):
    related_rows = src[ src['App'] == WORKLOAD[worki]]
    output_array[worki] = related_rows['Requests/s'].median()
print(query, "throughput:", sum(np.nan_to_num(output_array)))
print("\t[rps/cntr]", output_array)
    

[0, 1, 2, 0, 0, 4, 0, 0, 0] throughput: 5.825000000000001
	[rps/cntr] [  nan 0.98  4.365   nan   nan 0.48    nan   nan   nan]


In [139]:
WORKLOAD = ["SYS-CPU", "Redis", "MXNet-ResNet-Local", "MXNet-ResNet-Remote", "SYS-MEM", "SYS-FILEIO", "Stress-CPU", "Stress-MEM", "Stress-FILE"]
related_rows = src[ src['App'] == WORKLOAD[1]]

In [211]:
def query_results_check_csv_r1r2m1m2(query=[0, 2, 2, 0, 0, 4, 0, 0, 0]):
    # not correct in display, but can find the right file
    save_query = query.copy()
    query_input = reproduce_x_to_profile_setting([query],r1r2m1m2=True)
    print("query_input 8 containers with [CPU Redis ...] (not R1 R2 ..) :", query_input)
    filename = str(query_input[0]).replace(', ', '-')[1:-1]
    filename = 'results/'+filename+'.csv'
    try:
        src=pd.read_csv(filename)
    except:
        print("CSV file", filename, " not found")
        
    WORKLOAD = ["SYS-CPU", "Redis", "MXNet-ResNet-Local", "MXNet-ResNet-Remote", "SYS-MEM", "SYS-FILEIO", "Stress-CPU", "Stress-MEM", "Stress-FILE"]
    output_array = np.array([np.nan]*9)
    for worki in range(len(WORKLOAD)):
        related_rows = src[ src['App'] == WORKLOAD[worki]]
        output_array[worki] = related_rows['Requests/s'].median()
    print(save_query, "throughput:", sum(np.nan_to_num(output_array)))
    print("\t[rps/cntr]", output_array)
    return src

In [227]:
# query_results_check_csv_r1r2m1m2([0,1,0,0,0,1,0,0,1])
# query_results_check_csv_r1r2m1m2([1, 1, 2, 0, 0, 4, 0, 0, 0])
query_results_check_csv_r1r2m1m2([0, 1, 0, 0, 0, 1, 0, 0, 1])

query_input 8 containers with [CPU Redis ...] (not R1 R2 ..) : [[2, 0, 0, 0, 0, 0, 6, 9]]
[0, 1, 0, 0, 0, 1, 0, 0, 1] throughput: 1.4749999999999999
	[rps/cntr] [  nan 1.235   nan   nan   nan 0.09    nan   nan 0.15 ]


App  Port   Name  # requests    50%    66%    75%    80%    90%  \
0         Redis  8081  Total         738   2800   2900   3000   3100   3100   
1    SYS-FILEIO  8087  Total          24  91000  92000  92000  92000  93000   
2   Stress-FILE  8088  Total          44  57000  57000  57000  58000  58000   
3         Redis  8081  Total         744   2800   2900   3000   3000   3100   
4    SYS-FILEIO  8087  Total          25  91000  92000  92000  92000  92000   
5   Stress-FILE  8088  Total          44  56000  57000  57000  57000  58000   
6         Redis  8081  Total         733   2800   3000   3000   3100   3100   
7    SYS-FILEIO  8087  Total          79   2800   3100  92000  93000  94000   
8   Stress-FILE  8088  Total         125   1600   1700  56000  57000  58000   
9         Redis  8081  Total         748   2700   2900   2900   3000   3100   
10   SYS-FILEIO  8087  Total          88   2900  27000  71000  71000  72000   
11  Stress-FILE  8088  Total         132   1600   1800  50000  51000  51000   

      95%     ...      Method  Name.1  # requests.1 # failures  \
0    3200     ...        None   Total           738          0   
1   93000     ...        None   Total            24          0   
2   58000     ...        None   Total            44          0   
3    3100     ...        None   Total           744          0   
4   92000     ...        None   Total            25          0   
5   58000     ...        None   Total            44          0   
6    3200     ...        None   Total           733          0   
7   94000     ...        None   Total            79          0   
8   58000     ...        None   Total           125          0   
9    3100     ...        None   Total           748          0   
10  72000     ...        None   Total            88          0   
11  52000     ...        None   Total           132          0   

   Median response time  Average response time  Min response time  \
0                  2800                   2747               2013   
1                 91000                  86781              57073   
2                 56000                  52837               8524   
3                  2800                   2723               1969   
4                 91000                  85118              46535   
5                 56000                  51838               8600   
6                  2800                   2774               2044   
7                  2800                  28775               2111   
8                  1600                  17554               1374   
9                  2700                   2691               2001   
10                 2900                  25360               2004   
11                 1600                  16926               1369   

    Max response time  Average Content Size  Requests/s  
0                3649                    68        1.23  
1               93270                    99        0.05  
2               58203                     1        0.07  
3                3455                    68        1.24  
4               92796                    99        0.04  
5               58113                     1        0.08  
6                3875                    68        1.22  
7               94677                    98        0.13  
8               58978                     1        0.22  
9                3657                    68        1.25  
10              72654                    98        0.15  
11              53305                     1        0.22  

[12 rows x 23 columns]

In [140]:
related_rows

App  Port   Name  # requests   50%   66%   75%   80%   90%   95%  \
0  Redis  8081  Total         729  2800  2900  3000  3000  3200  3200   
2  Redis  8081  Total         751  2700  2800  2900  2900  3100  3200   
4  Redis  8081  Total         736  2700  2900  3000  3000  3100  3200   
6  Redis  8081  Total         744  2800  2900  3000  3000  3100  3200   

      ...      Method  Name.1  # requests.1 # failures Median response time  \
0     ...        None   Total           729          0                 2800   
2     ...        None   Total           751          0                 2700   
4     ...        None   Total           736          0                 2700   
6     ...        None   Total           744          0                 2800   

   Average response time  Min response time  Max response time  \
0                   2771               1989               3802   
2                   2685               1992               3684   
4                   2744               2036               4003   
6                   2732               1937               3536   

   Average Content Size  Requests/s  
0                    68        1.22  
2                    68        1.25  
4                    68        1.23  
6                    68        1.24  

[4 rows x 23 columns]

In [142]:
related_rows.median()['Requests/s']

1.2349999999999999

In [127]:
inarray

[[0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 2, 0, 0, 4, 0, 0, 0],
 [1, 0, 2, 1, 0, 0, 1, 2, 0],
 [1, 0, 0, 3, 0, 0, 1, 2, 0],
 [1, 4, 0, 0, 2, 0, 0, 0, 0],
 [1, 0, 1, 0, 1, 0, 1, 0, 0],
 [1, 0, 1, 0, 1, 0, 0, 1, 0],
 [1, 0, 1, 0, 0, 1, 0, 1, 0],
 [1, 0, 0, 1, 0, 1, 0, 1, 0],
 [0, 1, 0, 1, 0, 1, 0, 1, 0],
 [0, 1, 0, 1, 0, 1, 0, 0, 1],
 [0, 1, 0, 1, 0, 0, 1, 0, 1],
 [0, 0, 1, 0, 1, 0, 1, 0, 1],
 [4, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 4, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 4, 0, 0, 0, 0, 0, 0],
 [1, 0, 1, 0, 0, 0, 0, 2, 0],
 [0, 1, 0, 1, 2, 0, 1, 0, 0],
 [2, 0, 0, 0, 1, 0, 1, 0, 0],
 [0, 1, 1, 0, 0, 0, 2, 1, 1],
 [0, 1, 0, 2, 0, 2, 0, 0, 1],
 [0, 0, 0, 0, 0, 1, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 2, 0, 1, 1, 0, 0, 1],
 [0, 1, 0, 1, 0, 0, 0, 1, 0],
 [2, 0, 1, 0, 0, 1, 1, 1, 0],
 [0, 0, 0, 1, 0, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 1],
 [1, 0, 2, 1, 0, 1, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 2],
 [0, 1, 0, 1, 3, 1, 1, 0, 0]]

In [134]:
inarray=[[0, 1, 0, 0, 0, 0, 0, 0, 1],[0, 1, 0, 0, 0, 0, 0, 0, 1],[1, 1, 2, 0, 0, 4, 0, 0, 0],[1, 1, 2, 1, 0, 0, 1, 2, 0],[1, 1, 0, 3, 0, 0, 1, 2, 0],[1, 5, 0, 0, 2, 0, 0, 0, 0],[1, 1, 1, 0, 1, 0, 1, 0, 0],[1, 1, 1, 0, 1, 0, 0, 1, 0],[1, 1, 1, 0, 0, 1, 0, 1, 0],[1, 1, 0, 1, 0, 1, 0, 1, 0],[0, 2, 0, 1, 0, 1, 0, 1, 0],[0, 2, 0, 1, 0, 1, 0, 0, 1],[0, 2, 0, 1, 0, 0, 1, 0, 1],[0, 1, 1, 0, 1, 0, 1, 0, 1],[4, 1, 0, 0, 0, 0, 0, 0, 0],[0, 5, 0, 0, 0, 0, 0, 0, 0],[0, 1, 4, 0, 0, 0, 0, 0, 0],[1, 1, 1, 0, 0, 0, 0, 2, 0],[0, 2, 0, 1, 2, 0, 1, 0, 0],[2, 1, 0, 0, 1, 0, 1, 0, 0],[0, 2, 1, 0, 0, 0, 2, 1, 1],[0, 2, 0, 2, 0, 2, 0, 0, 1],[0, 1, 0, 0, 0, 1, 0, 0, 1],[1, 1, 0, 0, 0, 0, 0, 0, 0],[0, 1, 2, 0, 1, 1, 0, 0, 1],[0, 2, 0, 1, 0, 0, 0, 1, 0],[2, 1, 1, 0, 0, 1, 1, 1, 0],[0, 1, 0, 1, 0, 0, 1, 0, 0],[0, 1, 0, 0, 0, 1, 0, 0, 1],[1, 1, 2, 1, 0, 1, 0, 0, 1],[1, 1, 0, 0, 0, 0, 0, 0, 2],[0, 2, 0, 1, 3, 1, 1, 0, 0]]

In [135]:
inarray

[[0, 1, 0, 0, 0, 0, 0, 0, 1],
 [0, 1, 0, 0, 0, 0, 0, 0, 1],
 [1, 1, 2, 0, 0, 4, 0, 0, 0],
 [1, 1, 2, 1, 0, 0, 1, 2, 0],
 [1, 1, 0, 3, 0, 0, 1, 2, 0],
 [1, 5, 0, 0, 2, 0, 0, 0, 0],
 [1, 1, 1, 0, 1, 0, 1, 0, 0],
 [1, 1, 1, 0, 1, 0, 0, 1, 0],
 [1, 1, 1, 0, 0, 1, 0, 1, 0],
 [1, 1, 0, 1, 0, 1, 0, 1, 0],
 [0, 2, 0, 1, 0, 1, 0, 1, 0],
 [0, 2, 0, 1, 0, 1, 0, 0, 1],
 [0, 2, 0, 1, 0, 0, 1, 0, 1],
 [0, 1, 1, 0, 1, 0, 1, 0, 1],
 [4, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 5, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 4, 0, 0, 0, 0, 0, 0],
 [1, 1, 1, 0, 0, 0, 0, 2, 0],
 [0, 2, 0, 1, 2, 0, 1, 0, 0],
 [2, 1, 0, 0, 1, 0, 1, 0, 0],
 [0, 2, 1, 0, 0, 0, 2, 1, 1],
 [0, 2, 0, 2, 0, 2, 0, 0, 1],
 [0, 1, 0, 0, 0, 1, 0, 0, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 2, 0, 1, 1, 0, 0, 1],
 [0, 2, 0, 1, 0, 0, 0, 1, 0],
 [2, 1, 1, 0, 0, 1, 1, 1, 0],
 [0, 1, 0, 1, 0, 0, 1, 0, 0],
 [0, 1, 0, 0, 0, 1, 0, 0, 1],
 [1, 1, 2, 1, 0, 1, 0, 0, 1],
 [1, 1, 0, 0, 0, 0, 0, 0, 2],
 [0, 2, 0, 1, 3, 1, 1, 0, 0]]

In [136]:
inarray_back = inarray.copy()

In [137]:
import os
os.path.exists(filename)

False

In [138]:
for query in inarray:
    print("in: ", query)
    query_input = reproduce_x_to_profile_setting([query], with_redis=False)
    filename = str(query_input[0]).replace(', ', '-')[1:-1]
    filename = 'results/'+filename+'.csv'
    if not os.path.exists(filename):
        print(query)
        print(filename)

in:  [0, 1, 0, 0, 0, 0, 0, 0, 1]
in:  [0, 1, 0, 0, 0, 0, 0, 0, 1]
in:  [1, 1, 2, 0, 0, 4, 0, 0, 0]
[1, 1, 2, 0, 0, 4, 0, 0, 0]
results/1-2-3-3-6-6-6-6.csv
in:  [1, 1, 2, 1, 0, 0, 1, 2, 0]
[1, 1, 2, 1, 0, 0, 1, 2, 0]
results/1-2-3-3-4-7-8-8.csv
in:  [1, 1, 0, 3, 0, 0, 1, 2, 0]
[1, 1, 0, 3, 0, 0, 1, 2, 0]
results/1-2-4-4-4-7-8-8.csv
in:  [1, 5, 0, 0, 2, 0, 0, 0, 0]
[1, 5, 0, 0, 2, 0, 0, 0, 0]
results/1-2-2-2-2-2-5-5.csv
in:  [1, 1, 1, 0, 1, 0, 1, 0, 0]
[1, 1, 1, 0, 1, 0, 1, 0, 0]
results/1-0-0-0-2-3-5-7.csv
in:  [1, 1, 1, 0, 1, 0, 0, 1, 0]
[1, 1, 1, 0, 1, 0, 0, 1, 0]
results/1-0-0-0-2-3-5-8.csv
in:  [1, 1, 1, 0, 0, 1, 0, 1, 0]
[1, 1, 1, 0, 0, 1, 0, 1, 0]
results/1-0-0-0-2-3-6-8.csv
in:  [1, 1, 0, 1, 0, 1, 0, 1, 0]
[1, 1, 0, 1, 0, 1, 0, 1, 0]
results/1-0-0-0-2-4-6-8.csv
in:  [0, 2, 0, 1, 0, 1, 0, 1, 0]
[0, 2, 0, 1, 0, 1, 0, 1, 0]
results/2-0-0-0-2-4-6-8.csv
in:  [0, 2, 0, 1, 0, 1, 0, 0, 1]
[0, 2, 0, 1, 0, 1, 0, 0, 1]
results/2-0-0-0-2-4-6-9.csv
in:  [0, 2, 0, 1, 0, 0, 1, 0, 1]
[0, 2, 0, 1

In [139]:
ar_sim_in=[[0,1,0,0,2,0,0,0,1],[0,1,0,0,0,0,2,0,1],[0,1,0,0,0,0,0,0,1],[0,1,0,0,0,0,0,0,1],[1,1,2,0,0,4,0,0,0],[1,1,2,1,0,0,1,2,0],[0,1,0,0,0,0,0,0,0],[1,1,0,3,0,0,1,2,0],[1,5,0,0,2,0,0,0,0],[1,1,1,0,1,0,1,0,0],[1,1,1,0,1,0,0,1,0],[1,1,1,0,0,1,0,1,0],[1,1,0,1,0,1,0,1,0],[0,2,0,1,0,1,0,1,0],[0,2,0,1,0,1,0,0,1],[0,2,0,1,0,0,1,0,1],[0,2,0,0,1,0,1,0,1],[0,1,1,0,1,0,1,0,1],[4,1,0,0,0,0,0,0,0],[0,5,0,0,0,0,0,0,0],[0,1,4,0,0,0,0,0,0],[0,1,0,4,0,0,0,0,0],[0,1,0,0,4,0,0,0,0],[0,1,0,0,0,4,0,0,0],[0,1,0,0,0,0,4,0,0],[0,1,0,0,0,0,0,4,0],[0,1,0,0,0,0,0,0,4],[1,1,1,0,0,0,0,2,0],[0,2,0,1,2,0,1,0,0],[2,1,0,0,1,0,1,0,0],[0,2,1,0,0,0,2,1,1],[0,2,0,2,0,2,0,0,1],[0,1,0,0,0,1,0,0,1],[1,1,0,0,0,0,0,0,0],[0,1,2,0,1,1,0,0,1],[0,2,0,1,0,0,0,1,0],[2,1,1,0,0,1,1,1,0],[0,1,0,1,0,0,1,0,0],[0,1,0,0,0,0,0,2,0],[0,1,0,0,0,1,0,0,1],[1,1,2,1,0,1,0,0,1],[0,3,0,0,0,0,1,1,0],[1,1,0,0,0,0,0,0,2],[0,2,1,1,1,0,0,0,0],[0,2,0,1,3,1,1,0,0]]

In [142]:
output_xs = r1r2m1m2_to_mms_local_remote(np.array(ar_sim_in))

In [143]:
output_xs

array([[0, 1, 0, 0, 2, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 0, 2, 0, 1],
       [0, 1, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 0, 0, 0, 1],
       [0, 2, 2, 0, 0, 4, 0, 0, 0],
       [0, 2, 3, 0, 0, 0, 1, 2, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 3, 0, 0, 0, 1, 2, 0],
       [0, 6, 0, 0, 2, 0, 0, 0, 0],
       [0, 2, 1, 0, 1, 0, 1, 0, 0],
       [0, 2, 1, 0, 1, 0, 0, 1, 0],
       [0, 2, 1, 0, 0, 1, 0, 1, 0],
       [0, 2, 1, 0, 0, 1, 0, 1, 0],
       [0, 2, 1, 0, 0, 1, 0, 1, 0],
       [0, 2, 1, 0, 0, 1, 0, 0, 1],
       [0, 2, 1, 0, 0, 0, 1, 0, 1],
       [0, 2, 0, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 1, 0, 1, 0, 1],
       [0, 5, 0, 0, 0, 0, 0, 0, 0],
       [0, 5, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 4, 0, 0, 0, 0, 0],
       [0, 1, 4, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 4, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 4, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 4, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 4, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 4],
       [0, 2, 1, 0, 0, 0, 0,

In [144]:
def reproduce_x_to_profile_setting(array, with_redis=True, verbose=True):
  # date: 2019-0617
  # input: array, shape: (2, 9), e.g., [[2. 1. 0. 4. 0. 1. 0. 0. 0.]]
  # output: [[2, 1, 1, 4, 4, 4, 4, 6]]
    summary_setting = None
    for item in array:
        if with_redis:
            setting = [2]
            item[1] -= 1 # put 1 Redis at top
        else:
            setting = []

        for i in range(len(item)):
            if item[i] != 0:
                for num in range(item[i]):
                    setting.append(i+1)

        if len(setting) > 8: # over allocated
            print("[ERROR]: Too many containers: ", item)
        else:
            for i in range(8-len(setting)):
                setting.insert(1, 0) # add 0 after the first place

        if summary_setting is None:
          summary_setting = [setting]
        else:
          summary_setting.append(setting)

    return summary_setting


In [145]:
reproduce_x_to_profile_setting(output_xs)

[[2, 0, 0, 0, 0, 5, 5, 9],
 [2, 0, 0, 0, 0, 7, 7, 9],
 [2, 0, 0, 0, 0, 0, 0, 9],
 [2, 0, 0, 0, 0, 0, 0, 9],
 [2, 2, 3, 3, 6, 6, 6, 6],
 [2, 2, 3, 3, 3, 7, 8, 8],
 [2, 0, 0, 0, 0, 0, 0, 0],
 [2, 2, 3, 3, 3, 7, 8, 8],
 [2, 2, 2, 2, 2, 2, 5, 5],
 [2, 0, 0, 0, 2, 3, 5, 7],
 [2, 0, 0, 0, 2, 3, 5, 8],
 [2, 0, 0, 0, 2, 3, 6, 8],
 [2, 0, 0, 0, 2, 3, 6, 8],
 [2, 0, 0, 0, 2, 3, 6, 8],
 [2, 0, 0, 0, 2, 3, 6, 9],
 [2, 0, 0, 0, 2, 3, 7, 9],
 [2, 0, 0, 0, 2, 5, 7, 9],
 [2, 0, 0, 0, 4, 5, 7, 9],
 [2, 0, 0, 0, 2, 2, 2, 2],
 [2, 0, 0, 0, 2, 2, 2, 2],
 [2, 0, 0, 0, 4, 4, 4, 4],
 [2, 0, 0, 0, 3, 3, 3, 3],
 [2, 0, 0, 0, 5, 5, 5, 5],
 [2, 0, 0, 0, 6, 6, 6, 6],
 [2, 0, 0, 0, 7, 7, 7, 7],
 [2, 0, 0, 0, 8, 8, 8, 8],
 [2, 0, 0, 0, 9, 9, 9, 9],
 [2, 0, 0, 0, 2, 3, 8, 8],
 [2, 0, 0, 2, 3, 5, 5, 7],
 [2, 0, 0, 0, 2, 2, 5, 7],
 [2, 0, 2, 4, 7, 7, 8, 9],
 [2, 0, 2, 3, 3, 6, 6, 9],
 [2, 0, 0, 0, 0, 0, 6, 9],
 [2, 0, 0, 0, 0, 0, 0, 2],
 [2, 0, 0, 4, 4, 5, 6, 9],
 [2, 0, 0, 0, 0, 2, 3, 8],
 [2, 0, 2, 2, 3, 6, 7, 8],
 