# Step 1: import npzfile and check info

In [68]:
import matplotlib.pyplot as plt
import numpy as np

# npzfile = np.load('../datasets/0611-mms-175.npz')
npzfile = np.load('../datasets/0610-com-438.npz')
# npzfile = np.load('../datasets/0602-mss-revisit-135-results.npz')
# npzfile = np.load('../datasets/0509-com-444-results.npz')
# npzfile = np.load('../datasets/0601-mms-48-results.npz')
# npzfile = np.load('../datasets/0601-3_4_50cases-results.npz')
# npzfile = np.load('../datasets/0509-low-com-210-results.npz')
# npzfile = np.load('../datasets/0507-115-1-results.npz')
# npzfile = np.load('../datasets/0508-low-1-results.npz')
# npzfile = np.load('../datasets/0509-low-110-results.npz')

x, y1, y2, y3 = npzfile['alloc'], npzfile['rt_50'], npzfile['rt_99'], npzfile['rps']

In [69]:
len(x)

438

In [291]:
# npzfile = np.load('../datasets/0602-mss-revisit-135-results.npz') # AC
npzfile = np.load('../datasets/0601-mms-48-results.npz') # ACw
# npzfile = np.load('../datasets/0509-com-444-results.npz') # 6x0.5s
# [0.  0.5 0.  0.  0.  1.5 0.  0.  0. ]
# [0.  2.  0.  0.  1.  1.5 0.  0.5 1. ]
# [0.  1.  1.5 0.  0.  0.  0.  0.5 1. ]
# [0.  1.  0.5 0.  0.  0.  0.  0.5 0. ]
# [5.  1.  0.5 0.5 0.  0.  0.  0.  0. ]
# [3.  1.  0.5 0.5 0.  0.  2.  0.  0. ]


# npzfile = np.load('0601-mms-48-results.npz') # AC

# npzfile = np.load('0509-com-325-results.npz') # 4 x 0.5
# [0.  0.5 0.  0.  0.  1.5 0.  0.  0. ]
# [0.  2.  0.  0.  1.  1.5 0.  0.5 1. ]
# [0.  1.  1.5 0.  0.  0.  0.  0.5 1. ]
# [0.  1.  0.5 0.  0.  0.  0.  0.5 0. ]

# npzfile = np.load('0509-low-com-210-results.npz') # 1 x 0.5
# [0.  0.5 0.  0.  0.  1.5 0.  0.  0. ]

# npzfile=np.load('0509-low-110-results.npz') # 1 x 0.5
# [0.  0.5 0.  0.  0.  1.5 0.  0.  0. ]

# npzfile = np.load('0508-low-105-results.npz') # AC

# npzfile = np.load('0507-all-110-results.npz') # 3 x 0.5
# [0.  2.  0.  0.  1.  1.5 0.  0.5 1. ]
# [0.  1.  1.5 0.  0.  0.  0.  0.5 1. ]
# [0.  1.  0.5 0.  0.  0.  0.  0.5 0. ]

# npzfile = np.load('0507-115-1-results.npz')
# 23 [0.0, 2.0, 0.0, 0.0, 1.0, 1.5, 0.0, 0.5, 1.0]
# 41 [0.0, 1.0, 1.5, 0.0, 0.0, 0.0, 0.0, 0.5, 1.0]
# 98 [0.0, 1.0, 0.5, 0.0, 0.0, 0.0, 0.0, 0.5, 0.0]

# npzfile = np.load('0508-low-1-results.npz') # AC

# npzfile = np.load('0508-low-2-results.npz') 
# 41 [0.0, 0.5, 0.0, 0.0, 0.0, 1.5, 0.0, 0.0, 0.0]
# 51 [0.0, 1.0, 0.5, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0]

x, y1, y2, y3 = npzfile['alloc'], npzfile['rt_50'], npzfile['rt_99'], npzfile['rps']

# for item in x:
#     if 0.5 in item or 1.5 in item or 2.5 in item or 3.5 in item:
#         print(item)

In [70]:
for counter in range(len(x)):
    item = x[counter]
    if 0.5 in item or 1.5 in item or 2.5 in item or 3.5 in item or 4.5 in item:
        print(counter, list(item), list(y3[counter]))

In [71]:
x[40],y3[40]

(array([0., 1., 0., 0., 1., 0., 0., 0., 2.]),
 array([nan, 1.445, nan, nan, 3.4, nan, nan, nan, 0.38], dtype=object))

In [72]:
(x[40],x[237],x[254],
y3[40],y3[237],y3[254])

(array([0., 1., 0., 0., 1., 0., 0., 0., 2.]),
 array([0., 1., 3., 0., 1., 1., 0., 0., 2.]),
 array([2., 1., 2., 0., 0., 1., 0., 2., 0.]),
 array([nan, 1.445, nan, nan, 3.4, nan, nan, nan, 0.38], dtype=object),
 array([nan, 1.09, 3.55, nan, 2.585, 0.1, nan, nan, 0.08], dtype=object),
 array([1.805, 0.99, 2.875, nan, nan, 1.785, nan, 0.535, nan], dtype=object))

In [284]:
def remove_by_indices(list_of_array, indices):
    for index in range(len(list_of_array)):
        list_of_array[index] = np.delete(list_of_array[index], indices, 0)
    return list_of_array

In [285]:
len(x)

444

In [286]:
indices = (41, 238, 256, 313, 422, 423)
x, y1, y2, y3 = remove_by_indices([x, y1, y2, y3], indices)

In [289]:
len(x)

438

In [288]:
(x[40],x[236],x[252],
y3[40],y3[236],y3[252])

(array([0., 1., 0., 0., 1., 0., 0., 0., 2.]),
 array([0., 1., 2., 2., 2., 0., 0., 0., 1.]),
 array([0., 2., 2., 0., 1., 1., 0., 0., 2.]),
 array([nan, 1.445, nan, nan, 3.4, nan, nan, nan, 0.38], dtype=object),
 array([nan, 1.115, 2.875, 3.06, 2.76, nan, nan, nan, 1.775], dtype=object),
 array([nan, 1.185, 3.925, nan, 2.645, 0.1, nan, nan, 0.09], dtype=object))

In [290]:
filename='../datasets/0610-combined-438-results-fix_of_444.npz'
np.savez(filename,alloc=x,rt_50=y1, rt_99=y2, rps=y3)

In [9]:
# npzfile = np.load('0507-all-110-results.npz')
# x, y1, y2, y3 = npzfile['alloc'], npzfile['rt_50'], npzfile['rt_99'], npzfile['rps']
# npzfile = np.load('0508-low-105-results.npz')
# x_, y1_, y2_, y3_ = npzfile['alloc'], npzfile['rt_50'], npzfile['rt_99'], npzfile['rps']

# x__ = np.append(x, x_, axis=0)
# y1__ = np.append(y1, y1_, axis=0)
# y2__ = np.append(y2, y2_, axis=0)
# y3__ = np.append(y3, y3_, axis=0)

# np.savez('0508-com-215-results.npz',alloc=x__,rt_50=y1__, rt_99=y2__, rps=y3__)

In [10]:
len(x), len(y1), len(y2), len(y3)

(135, 135, 135, 135)

In [11]:
xnew, y1new, y2new, y3new = x, y1, y2, y3

------
another

------

In [74]:

# npzfile = np.load('../datasets/0602-mss-revisit-135-results.npz') # AC
npzfile = np.load('../datasets/0611-mms-175.npz')
xnew, y1new, y2new, y3new = npzfile['alloc'], npzfile['rt_50'], npzfile['rt_99'], npzfile['rps']
print(len(xnew))

# npzfile = np.load('../datasets/0509-com-444-results.npz')
npzfile = np.load('../datasets/0610-com-438.npz')
xori, y1ori, y2ori, y3ori = npzfile['alloc'], npzfile['rt_50'], npzfile['rt_99'], npzfile['rps']
print(len(xori))

175
438


In [76]:
def ndarray_match(x1, x2, as_int=True, verbose=0):
    if as_int:
        x1=x1.astype(int)
        x2=x2.astype(int)
    list_x1=x1.tolist()
    list_x2=x2.tolist()
    
    match_dict={}
    for x1_index in range(len(list_x1)):
        item = list_x1[x1_index]
        try:
            x2_index = list_x2.index(item)
            if verbose:
                print("x1[{}]==x2[{}]".format(x1_index, x2_index))
            match_dict[x1_index] = x2_index
        except ValueError:
            pass
    return match_dict

def display_matched_items(x1, x2, y1, y2, top=None):
    match_dict = ndarray_match(x1, x2)
    try:
        match_dict_items = list(match_dict.items())[:top]
    except:
        match_dict_items = match_dict.items()
    for (i,j) in match_dict_items:
        print(x1[i],x2[j])
        print(y1[i])
        print(y2[j])
        print()


In [77]:
match_dict=ndarray_match(xnew, xori, 0, 1)

x1[2]==x2[109]
x1[6]==x2[7]
x1[10]==x2[112]
x1[13]==x2[226]
x1[27]==x2[121]
x1[28]==x2[20]
x1[33]==x2[26]
x1[38]==x2[27]
x1[40]==x2[28]
x1[48]==x2[31]
x1[53]==x2[128]
x1[54]==x2[129]
x1[60]==x2[132]
x1[64]==x2[42]
x1[65]==x2[25]
x1[76]==x2[140]
x1[79]==x2[141]
x1[80]==x2[51]
x1[82]==x2[89]
x1[83]==x2[53]
x1[87]==x2[54]
x1[88]==x2[145]
x1[89]==x2[276]
x1[90]==x2[148]
x1[95]==x2[155]
x1[96]==x2[60]
x1[102]==x2[161]
x1[103]==x2[65]
x1[104]==x2[162]
x1[105]==x2[163]
x1[106]==x2[169]
x1[107]==x2[71]
x1[111]==x2[72]
x1[112]==x2[172]
x1[115]==x2[174]
x1[119]==x2[175]
x1[124]==x2[177]
x1[125]==x2[76]
x1[126]==x2[179]
x1[128]==x2[77]
x1[134]==x2[190]
x1[135]==x2[14]
x1[136]==x2[83]
x1[140]==x2[84]
x1[143]==x2[88]
x1[147]==x2[90]
x1[148]==x2[196]
x1[151]==x2[197]
x1[152]==x2[326]
x1[154]==x2[93]
x1[155]==x2[199]
x1[157]==x2[200]
x1[160]==x2[202]
x1[163]==x2[205]
x1[165]==x2[2]
x1[172]==x2[22]
x1[173]==x2[212]


In [78]:
[[len(xnew), len(y1new), len(y2new), len(y3new)],
[len(xori), len(y1ori), len(y2ori), len(y3ori)],
[len(match_dict)]]

[[175, 175, 175, 175], [438, 438, 438, 438], [57]]

In [79]:
display_matched_items(xnew, xori, y3new, y3ori)

[1. 1. 0. 1. 0. 0. 0. 0. 1.] [1. 1. 0. 1. 0. 0. 0. 0. 1.]
[1.785 1.005 nan 3.77 nan nan nan nan 2.405]
[2.19 1.395 nan 4.52 nan nan nan nan 4.46]

[0. 1. 0. 1. 0. 1. 1. 0. 0.] [0. 1. 0. 1. 0. 1. 1. 0. 0.]
[nan 1.01 nan 3.575 nan 0.135 0.595 nan nan]
[nan 1.415 nan 4.225 nan 0.17 0.64 nan nan]

[1. 1. 0. 1. 0. 0. 0. 1. 0.] [1. 1. 0. 1. 0. 0. 0. 1. 0.]
[1.89 0.94 nan 3.59 nan nan nan 0.82 nan]
[2.19 1.335 nan 4.19 nan nan nan 0.72 nan]

[0. 1. 1. 0. 1. 1. 0. 1. 0.] [0. 1. 1. 0. 1. 1. 0. 1. 0.]
[nan 0.895 3.665 nan 2.88 1.455 nan 0.81 nan]
[nan 1.105 3.105 nan 3.375 0.14 nan 0.725 nan]

[0. 1. 0. 1. 0. 0. 0. 0. 1.] [0. 1. 0. 1. 0. 0. 0. 0. 1.]
[nan 0.945 nan 3.67 nan nan nan nan 0.665]
[nan 1.435 nan 4.115 nan nan nan nan 4.6]

[0. 1. 1. 0. 1. 0. 0. 0. 1.] [0. 1. 1. 0. 1. 0. 0. 0. 1.]
[nan 1.055 4.47 nan 2.97 nan nan nan 0.94]
[nan 1.415 4.23 nan 3.33 nan nan nan 5.305]

[0. 1. 0. 0. 1. 1. 1. 0. 0.] [0. 1. 0. 0. 1. 1. 1. 0. 0.]
[nan 1.235 nan nan 3.005 1.47 0.62 nan nan]
[nan 1.405 nan na

In [145]:
list(match_dict.items())[:None]

[(4, 4),
 (11, 99),
 (12, 4),
 (14, 328),
 (15, 328),
 (28, 296),
 (36, 23),
 (38, 296),
 (40, 293),
 (42, 23),
 (50, 23),
 (51, 326),
 (68, 328),
 (82, 293),
 (96, 99),
 (105, 293),
 (122, 99),
 (124, 337),
 (127, 4)]

In [183]:
np.where(xori[1]>0)

(array([1, 3]),)

In [190]:
for item in xori:
    if item[1] > 0:
        print(item)

[0. 2. 0. 0. 1. 0. 0. 0. 1.]
[0. 1. 0. 3. 0. 0. 0. 0. 0.]
[0. 1. 0. 1. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 1. 0. 2.]
[0. 1. 0. 1. 0. 0. 0. 1. 5.]
[0. 1. 0. 1. 0. 0. 0. 2. 4.]
[0. 1. 0. 0. 0. 0. 3. 0. 0.]
[0. 1. 0. 1. 0. 1. 1. 0. 0.]
[0. 1. 0. 2. 1. 0. 0. 0. 0.]
[0. 2. 0. 0. 1. 0. 0. 1. 4.]
[0. 2. 0. 0. 0. 0. 1. 1. 0.]
[0. 1. 0. 2. 0. 0. 1. 0. 0.]
[0. 1. 2. 0. 0. 0. 0. 0. 1.]
[0. 1. 2. 0. 0. 0. 0. 1. 4.]
[0. 1. 0. 1. 0. 1. 0. 0. 0.]
[0. 2. 0. 0. 0. 0. 1. 0. 1.]
[0. 1. 1. 0. 0. 0. 1. 1. 4.]
[0. 2. 1. 0. 0. 0. 0. 0. 1.]
[0. 2. 1. 0. 0. 0. 0. 1. 0.]
[0. 1. 1. 0. 0. 0. 1. 0. 1.]
[0. 1. 1. 0. 1. 0. 0. 0. 1.]
[0. 1. 0. 0. 0. 1. 0. 0. 2.]
[0. 1. 0. 0. 1. 0. 0. 0. 0.]
[0. 1. 0. 0. 1. 0. 0. 1. 5.]
[0. 1. 0. 0. 0. 1. 2. 0. 0.]
[0. 1. 0. 0. 1. 0. 0. 1. 0.]
[0. 1. 0. 0. 1. 1. 1. 0. 0.]
[0. 1. 1. 0. 1. 0. 0. 1. 0.]
[0. 1. 0. 1. 1. 0. 1. 0. 0.]
[0. 2. 0. 0. 0. 1. 0. 1. 0.]
[0. 2. 0. 0. 0. 1. 0. 0. 1.]
[0. 1. 0. 1. 1. 1. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 1. 1. 1.]
[0. 1. 0. 1. 0. 0. 0. 0. 2.]
[0. 2. 0. 1. 0

In [252]:
npzfile = np.load('0509-com-444-results.npz')
xori, y1ori, y2ori, y3ori = npzfile['alloc'], npzfile['rt_50'], npzfile['rt_99'], npzfile['rps']
print(len(xori))

444


SyntaxError: invalid syntax (<ipython-input-255-003db473ef70>, line 1)

In [259]:
xnew

array([[0., 2., 1., ..., 1., 0., 3.],
       [1., 1., 0., ..., 0., 0., 5.],
       [0., 2., 0., ..., 1., 1., 3.],
       ...,
       [0., 1., 1., ..., 0., 1., 3.],
       [0., 1., 0., ..., 0., 0., 6.],
       [2., 1., 0., ..., 1., 0., 3.]])

In [48]:

y1[0:10] # 50% response time
y2[0:10] # 99% response time
y3[0:10] # request per second
x[0:10] # allocation

array([[0., 2., 1., 1., 0., 0., 1., 0., 0.],
       [2., 3., 3., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 1., 0., 0., 0., 0., 1.],
       [0., 2., 0., 0., 1., 0., 1., 1., 0.],
       [1., 1., 0., 1., 1., 0., 1., 0., 0.],
       [0., 1., 0., 1., 0., 0., 0., 1., 1.],
       [0., 1., 0., 1., 0., 1., 1., 0., 0.],
       [0., 1., 4., 0., 0., 0., 0., 0., 0.],
       [1., 4., 0., 2., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 1., 0., 1., 1., 1.]])

In [57]:
for i in range(55,60):
    for j in range(9):
        print(x[i][j], y3[i][j])
    print()

0.0 nan
1.0 0.96
0.0 nan
0.0 nan
1.0 2.31
0.0 nan
0.0 nan
1.0 0.82
2.0 2.135

2.0 1.74
3.0 0.905
1.0 3.13
2.0 2.84
0.0 nan
0.0 nan
0.0 nan
0.0 nan
0.0 nan

0.0 nan
1.0 0.74
0.0 nan
1.0 3.295
2.0 2.615
0.0 nan
0.0 nan
1.0 0.805
1.0 2.275

0.0 nan
3.0 1.04
5.0 3.1
0.0 nan
0.0 nan
0.0 nan
0.0 nan
0.0 nan
0.0 nan

0.0 nan
1.0 0.71
2.0 3.94
0.0 nan
1.0 2.865
1.0 1.165
0.0 nan
0.0 nan
1.0 2.015



In [84]:
retest=x[(x[:,3]!=0) + (x[:,4]!=0)]

In [103]:
# dataset_x_to_profile_setting(retest)

In [113]:
to_print_list=[]
# set(retest_setting)
for item in retest_setting:
  to_print=[str(j) for j in item[1:]]
  to_print_list.append('-'.join(to_print))

In [120]:
for item in set(to_print_list):
  print(item, end=' ')
print('\n',len(set(to_print_list)))

0-0-0-3-4-5-5 0-3-4-6-6-8-9 0-0-0-0-3-4-8 0-0-2-4-5-7-9 0-0-3-3-5-6-9 0-0-1-3-4-5-6 0-0-0-0-1-1-7 0-0-0-0-4-7-9 0-0-0-0-0-4-9 0-0-0-0-0-4-5 0-1-5-6-8-9-9 0-4-4-5-6-7-9 0-0-0-1-4-8-8 0-0-0-0-0-4-7 0-0-0-0-1-3-5 0-0-1-5-9-9-9 0-1-2-3-5-6-7 0-0-0-1-1-5-7 0-0-0-3-4-8-9 0-0-1-4-5-7-9 0-0-0-1-4-5-7 0-0-0-0-4-6-7 0-0-0-0-4-8-9 0-0-0-3-5-9-9 0-0-0-0-0-1-5 0-0-0-1-3-4-5 0-0-1-3-4-5-8 0-0-0-1-3-4-8 0-0-1-3-4-8-8 0-0-0-0-0-2-4 0-0-0-0-3-5-8 0-0-1-3-4-5-9 0-0-0-0-0-3-4 0-0-1-3-3-3-4 0-0-4-5-5-8-9 0-0-0-0-0-0-5 0-0-1-4-7-8-9 0-0-0-0-4-6-9 0-0-0-0-1-5-7 0-0-0-0-4-7-8 0-0-0-2-4-9-9 0-0-0-0-3-5-7 0-0-0-0-1-5-9 0-0-0-0-4-5-6 0-0-0-5-8-9-9 0-0-0-4-6-6-9 0-0-1-4-8-8-9 0-0-1-1-3-4-7 0-0-1-3-4-7-7 0-0-0-0-0-4-4 0-0-0-4-5-8-9 0-0-0-2-3-5-9 0-0-0-0-1-4-8 0-0-0-0-4-6-8 0-0-0-1-1-3-4 0-0-0-0-0-5-9 0-0-0-3-4-5-9 0-0-0-0-1-1-1 0-0-0-0-1-4-9 0-0-0-3-5-6-8 0-0-1-3-5-6-7 0-0-0-0-5-6-7 0-0-0-1-2-4-9 0-0-0-0-3-5-5 0-0-0-0-1-4-7 0-0-0-4-6-8-9 0-0-1-1-1-3-4 0-0-0-3-5-6-9 0-0-0-2-4-5-8 0-0-0-3-5-7-9 0-0-0-0-1-4-6 0-0-0-

In [121]:
fourty_eight_setting=['2-2-2-2-2-3-4','2-2-3-3-3-3-3','1-1-2-2-2-3-4','0-1-1-1-2-3-4','0-1-2-2-3-4-4','2-2-2-2-2-2-3','0-0-1-1-3-4-4','1-1-1-1-1-4-4','0-0-0-0-0-3-4','0-1-1-1-1-3-4','1-3-3-3-4-4-4','1-1-2-2-2-2-3','0-1-2-3-4-4-4','0-3-3-3-3-3-3','1-1-1-1-1-2-4','0-0-0-2-2-3-3','3-3-3-3-4-4-4','0-0-3-3-3-4-4','3-3-3-3-4-4-4','0-0-0-3-3-3-3','0-1-1-3-3-3-4','0-1-1-1-4-4-4','0-1-1-2-3-4-4','0-0-2-2-2-3-3','0-1-2-2-2-4-4','3-3-3-4-4-4-4','0-0-0-0-1-4-4','0-2-4-4-4-4-4','1-1-2-2-3-3-3','0-0-4-4-4-4-4','0-0-1-2-2-2-4','1-2-3-3-3-3-4','2-2-3-3-3-3-4','0-0-0-0-0-1-4','0-1-1-1-2-2-3','0-0-2-3-3-4-4','2-4-4-4-4-4-4','2-2-4-4-4-4-4','0-0-0-0-1-3-3','2-2-2-2-2-2-4','1-1-2-3-3-3-4','0-0-0-3-3-3-4','0-0-0-1-3-3-3','2-2-2-3-3-4-4','0-1-1-1-1-1-3','0-1-1-1-2-2-3','0-0-0-0-2-3-4','1-2-2-2-2-2-4','2-2-2-2-3-3-4','1-1-2-2-3-4-4']

In [125]:
for item in fourty_eight_setting:
  if item in to_print_list:
    print(item)

0-0-0-0-0-3-4
0-0-0-0-0-1-4


In [45]:
even_number = (np.sum(x, axis=1) % 2 == 0)
len(x[~even_number])

0

In [21]:
# if still exists odd x, remove them for all x, y1, y2, y3
even_number

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [22]:
even_number = (np.sum(x, axis=1) % 2 == 0)

In [23]:
len(x)

106

In [35]:
x

array([[2., 3., 3., 0., 0., 0., 0., 0., 0.],
       [0., 1., 4., 0., 0., 0., 0., 0., 0.],
       [1., 4., 0., 2., 0., 0., 0., 0., 0.],
       [3., 1., 0., 3., 0., 0., 0., 0., 0.],
       [2., 4., 1., 1., 0., 0., 0., 0., 0.],
       [0., 1., 3., 1., 0., 0., 0., 0., 0.],
       [0., 1., 3., 2., 0., 0., 0., 0., 0.],
       [0., 2., 8., 6., 0., 0., 0., 0., 0.],
       [0., 1., 0., 5., 0., 0., 0., 0., 0.],
       [1., 3., 1., 2., 0., 0., 0., 0., 0.],
       [0., 3., 0., 5., 0., 0., 0., 0., 0.],
       [0., 1., 3., 4., 0., 0., 0., 0., 0.],
       [0., 1., 6., 0., 0., 0., 0., 0., 0.],
       [2., 2., 1., 2., 0., 0., 0., 0., 0.],
       [0., 3., 4., 1., 0., 0., 0., 0., 0.],
       [2., 3., 1., 2., 0., 0., 0., 0., 0.],
       [0., 3., 5., 0., 0., 0., 0., 0., 0.],
       [2., 5., 1., 0., 0., 0., 0., 0., 0.],
       [2., 1., 1., 2., 0., 0., 0., 0., 0.],
       [2., 2., 3., 1., 0., 0., 0., 0., 0.],
       [2., 1., 3., 1., 0., 0., 0., 0., 0.],
       [1., 6., 0., 1., 0., 0., 0., 0., 0.],
       [0.

# Step 2: Checking which logs need fix

In [86]:
def dataset_x_to_profile_setting(array, verbose=True):
  # array = x[~even_number][:2] # shape: (2, 9)

  summary_setting = None
  for item in array:
    setting = [2] # the first 2 is necessary
    for i in range(len(item)):
      if item[i] != 0:
        repeat_time = int(round(item[i]/2 + 0.001)) # make 3/2 => 2
        if verbose and item[i] % 2 != 0:
          print("%s, %d: %.3f => %d; " % (item, i+1, item[i], repeat_time), end='')
        if i == 1: # i.e., minus 1 repeat_time for '2'
          repeat_time -= 1
        for num in range(repeat_time):
          setting.append(i+1)
    if len(setting) < 8: # not occupying all slots
      # workload specific: inserting "0" after the first "2".
      for i in range(8-len(setting)):
        setting.insert(1, 0)
    # end of setting building
    if verbose:
      print(setting)

    if summary_setting is None:
      summary_setting = [setting]
    else:
      summary_setting.append(setting)

  summary_setting.sort()
  if verbose:
    print(summary_setting)

  return summary_setting

  

In [13]:
summary_setting = dataset_x_to_profile_setting(x[~even_number])
summary_setting

[0. 2. 0. 2. 0. 0. 0. 1. 2.], 8: 1.000 => 1; [2, 0, 0, 0, 0, 4, 8, 9]
[0. 2. 0. 2. 0. 0. 0. 3. 0.], 8: 3.000 => 2; [2, 0, 0, 0, 0, 4, 8, 8]
[0. 4. 0. 0. 2. 0. 0. 1. 0.], 8: 1.000 => 1; [2, 0, 0, 0, 0, 2, 5, 8]
[0. 2. 3. 0. 0. 0. 0. 2. 0.], 3: 3.000 => 2; [2, 0, 0, 0, 0, 3, 3, 8]
[0. 2. 2. 0. 0. 0. 2. 1. 0.], 8: 1.000 => 1; [2, 0, 0, 0, 0, 3, 7, 8]
[0. 2. 0. 0. 2. 0. 0. 1. 2.], 8: 1.000 => 1; [2, 0, 0, 0, 0, 5, 8, 9]
[0. 4. 0. 2. 0. 0. 0. 1. 0.], 8: 1.000 => 1; [2, 0, 0, 0, 0, 2, 4, 8]
[0. 2. 0. 0. 0. 0. 2. 3. 0.], 8: 3.000 => 2; [2, 0, 0, 0, 0, 7, 8, 8]
[0. 2. 2. 0. 0. 2. 0. 1. 0.], 8: 1.000 => 1; [2, 0, 0, 0, 0, 3, 6, 8]
[0. 2. 1. 0. 0. 2. 0. 0. 2.], 3: 1.000 => 1; [2, 0, 0, 0, 0, 3, 6, 9]
[0. 2. 2. 0. 0. 0. 0. 3. 0.], 8: 3.000 => 2; [2, 0, 0, 0, 0, 3, 8, 8]
[0. 4. 0. 0. 0. 0. 0. 3. 0.], 8: 3.000 => 2; [2, 0, 0, 0, 0, 2, 8, 8]
[0. 2. 0. 0. 0. 2. 2. 1. 0.], 8: 1.000 => 1; [2, 0, 0, 0, 0, 6, 7, 8]
[0. 2. 3. 0. 2. 0. 0. 0. 0.], 3: 3.000 => 2; [2, 0, 0, 0, 0, 3, 3, 5]
[0. 2. 0. 2. 0. 2. 0

[[2, 0, 0, 0, 0, 2, 4, 8],
 [2, 0, 0, 0, 0, 2, 5, 8],
 [2, 0, 0, 0, 0, 2, 8, 8],
 [2, 0, 0, 0, 0, 3, 3, 5],
 [2, 0, 0, 0, 0, 3, 3, 8],
 [2, 0, 0, 0, 0, 3, 6, 8],
 [2, 0, 0, 0, 0, 3, 6, 9],
 [2, 0, 0, 0, 0, 3, 7, 8],
 [2, 0, 0, 0, 0, 3, 8, 8],
 [2, 0, 0, 0, 0, 4, 4, 8],
 [2, 0, 0, 0, 0, 4, 6, 8],
 [2, 0, 0, 0, 0, 4, 8, 8],
 [2, 0, 0, 0, 0, 4, 8, 9],
 [2, 0, 0, 0, 0, 5, 8, 9],
 [2, 0, 0, 0, 0, 6, 7, 8],
 [2, 0, 0, 0, 0, 7, 8, 8]]

1. Run pyscript_1 to the fix-log

2. Copy these .csv files to summary folder.

3. Rerun pyscript_2 and _3 to collect new .npz

4. Import new .npz into this notebook again.

# Step 3: After fix, still wrong, please remove them

In [44]:
def remove_odd_records(x, y1, y2, y3):
  even_number = (np.sum(x, axis=1) % 2 == 0)
  indices = np.where(~even_number)
  x = np.delete(x, indices, 0)
  y1 = np.delete(y1, indices, 0)
  y2 = np.delete(y2, indices, 0)
  y3 = np.delete(y3, indices, 0)
  return x, y1, y2, y3

In [45]:
x,y1,y2,y3=remove_odd_records(x, y1, y2, y3)

And save to new .npz file

In [36]:
# np.savez('0507-115-1-results.npz',alloc=x,rt_50=y1, rt_99=y2, rps=y3)
# np.savez('0508-low-1-results.npz',alloc=x,rt_50=y1, rt_99=y2, rps=y3)
# np.savez('0508-low-110-results.npz',alloc=x,rt_50=y1, rt_99=y2, rps=y3)
# np.savez('dataset-0423x2-0424x2-0425x2-median.npz',alloc=x,rt_50=y1, rt_99=y2, rps=y3)
np.savez('0601-mms-48-results.npz',alloc=x,rt_50=y1, rt_99=y2, rps=y3)


# Step 4: Combine different npz files into one

In [293]:
one = '0601-mms-48-results.npz'
two = '0602-mss-revisit-135-results.npz'

npzfile = np.load(one)
x_one, y1_one, y2_one, y3_one = npzfile['alloc'], npzfile['rt_50'], npzfile['rt_99'], npzfile['rps']

npzfile = np.load(two)
x_two, y1_two, y2_two, y3_two = npzfile['alloc'], npzfile['rt_50'], npzfile['rt_99'], npzfile['rps']

x_com = np.append(x_one, x_two, axis=0)
y1_com = np.append(y1_one, y1_two, axis=0)
y2_com = np.append(y2_one, y2_two, axis=0)
y3_com = np.append(y3_one, y3_two, axis=0)

In [294]:
len(x_com),len(y1_com),len(y2_com),len(y3_com)

(183, 183, 183, 183)

In [295]:
com = '0610-mms-com-183-results.npz'

In [296]:
np.savez(com,alloc=x_com,rt_50=y1_com, rt_99=y2_com, rps=y3_com)

In [334]:
def find_self_duplicate(x, verbose=1):
    temp_set=set()
    duplicate_dict={}
    x_list = x.tolist()
    for index in range(len(x_list)):
        item_list = x_list[index]
        item_str = str(item_list)
        if item_str in temp_set:
            if verbose:
                first_occur_index = x_list.index(item_list)
                print(index, x[index], first_occur_index)
            duplicate_dict[index] = first_occur_index
        temp_set.add(item_str)
    return duplicate_dict

In [338]:
duplicate_dict=find_self_duplicate(x_two)

12 [0. 1. 0. 1. 0. 0. 0. 1. 5.] 4
15 [1. 1. 1. 1. 0. 0. 0. 0. 4.] 14
38 [1. 1. 0. 0. 1. 1. 0. 1. 3.] 28
42 [0. 1. 0. 0. 1. 0. 0. 1. 5.] 36
50 [0. 1. 0. 0. 1. 0. 0. 1. 5.] 36
66 [0. 1. 0. 0. 1. 0. 1. 0. 5.] 61
68 [1. 1. 1. 1. 0. 0. 0. 0. 4.] 14
74 [0. 1. 1. 1. 1. 0. 0. 0. 4.] 44
77 [1. 1. 0. 1. 1. 0. 1. 0. 3.] 3
81 [0. 1. 0. 1. 1. 0. 0. 1. 4.] 72
82 [1. 1. 0. 0. 1. 0. 0. 0. 5.] 40
84 [0. 1. 1. 0. 1. 0. 0. 0. 5.] 21
86 [0. 1. 1. 0. 1. 0. 0. 0. 5.] 21
92 [0. 1. 1. 1. 1. 0. 0. 0. 4.] 44
93 [0. 1. 0. 1. 1. 1. 1. 0. 3.] 76
95 [0. 1. 0. 1. 1. 0. 0. 0. 5.] 83
96 [0. 1. 0. 1. 0. 1. 0. 1. 4.] 11
98 [1. 1. 1. 1. 0. 1. 0. 0. 3.] 70
100 [0. 1. 1. 1. 0. 0. 0. 1. 4.] 49
104 [0. 1. 1. 0. 1. 1. 0. 0. 4.] 10
105 [1. 1. 0. 0. 1. 0. 0. 0. 5.] 40
108 [0. 1. 0. 0. 1. 1. 0. 0. 5.] 62
110 [1. 1. 1. 1. 1. 0. 0. 0. 3.] 106
113 [0. 1. 1. 0. 1. 0. 1. 0. 4.] 39
114 [0. 1. 0. 1. 0. 0. 1. 0. 5.] 85
117 [0. 1. 0. 1. 0. 1. 0. 0. 5.] 103
121 [0. 2. 0. 1. 0. 0. 0. 0. 5.] 109
122 [0. 1. 0. 1. 0. 1. 0. 1. 4.] 11
125 [1. 1

In [343]:
x_two[133],x_two[46],y3_two[133],y3_two[46]

(array([0., 1., 0., 0., 1., 0., 0., 0., 6.]),
 array([0., 1., 0., 0., 1., 0., 0., 0., 6.]),
 array([nan, 1.23, nan, nan, 2.985, nan, nan, nan, nan], dtype=object),
 array([nan, 1.21, nan, nan, 2.955, nan, nan, nan, 2.39], dtype=object))

In [344]:
x_two[132],x_two[9],y3_two[132],y3_two[9]

(array([0., 1., 1., 0., 1., 1., 0., 1., 3.]),
 array([0., 1., 1., 0., 1., 1., 0., 1., 3.]),
 array([nan, 0.74, 4.39, nan, 2.325, 0.8, nan, 0.8, 1.245], dtype=object),
 array([nan, 0.895, 3.665, nan, 2.88, 1.455, nan, 0.81, nan], dtype=object))

In [341]:
indices=list(duplicate_dict.keys())

In [328]:
x_com[60]

array([0., 1., 0., 1., 0., 0., 0., 1., 5.])

In [326]:
x_com[52]

array([0., 1., 0., 1., 0., 0., 0., 1., 5.])

# Fix non-even problem

In [53]:
npzfile_path_list = ['dataset-0423x2-0424x2-0425x2-median.npz']

In [54]:
for one in npzfile_path_list:
  npzfile = np.load(one)
  x, y1, y2, y3 = npzfile['alloc'], npzfile['rt_50'], npzfile['rt_99'], npzfile['rps']
  x = x / 2
  np.savez(one, alloc=x ,rt_50=y1, rt_99=y2, rps=y3)

Translate R1,R2,M1,M2 into 3,4

In [2]:
input_x = [1, 0, 1, 0, 1, 1, 0, 1, 3] # R1, R2, M1, M2, XXXXX
output_x = [0., 1., 1., 0., 1., 1., 0., 1., 3.] # CPU, Redis, MMS_LOCAL, MMS_REMOTE, XXXXX

In [4]:
output_x = input_x.copy()

num_redis = input_x[0] + input_x[1]  # Redis = R1 + R2
num_mms_local = 0
num_mms_remote = 0

if input_x[0] >= 1:  # if R1 exists
    num_mms_local += input_x[2]  # MMS_LOCAL += R1
else:
    num_mms_remote += input_x[2]  # MMS_REMOTE += R1

if input_x[1] >= 1:  # if R2 exists
    num_mms_local += input_x[3]  # MMS_LOCAL += R2
else:
    num_mms_remote += input_x[3]  # MMS_REMOTE += R2

output_x[0] = 0  # CPU = 0, discarded
output_x[1] = num_redis
output_x[2] = num_mms_local
output_x[3] = num_mms_remote

print(output_x)

[0, 1, 1, 0, 1, 1, 0, 1, 3]


In [5]:
input_x[-5:]

[1, 1, 0, 1, 3]

### Remove old 3 or 4 workload

In [81]:
len(xori)

438

In [82]:
indices=[]
for i in range(len(xori)):
    if xori[i][2] != 0 or xori[i][3] !=0:
        indices.append(i)
        print(xori[i])

[0. 1. 0. 3. 0. 0. 0. 0. 0.]
[0. 1. 0. 1. 0. 0. 0. 0. 0.]
[0. 1. 0. 1. 0. 0. 0. 1. 5.]
[0. 1. 0. 1. 0. 0. 0. 2. 4.]
[0. 1. 0. 1. 0. 1. 1. 0. 0.]
[0. 1. 0. 2. 1. 0. 0. 0. 0.]
[0. 1. 0. 2. 0. 0. 1. 0. 0.]
[0. 1. 2. 0. 0. 0. 0. 0. 1.]
[0. 1. 2. 0. 0. 0. 0. 1. 4.]
[0. 1. 0. 1. 0. 1. 0. 0. 0.]
[0. 1. 1. 0. 0. 0. 1. 1. 4.]
[0. 2. 1. 0. 0. 0. 0. 0. 1.]
[0. 2. 1. 0. 0. 0. 0. 1. 0.]
[0. 1. 1. 0. 0. 0. 1. 0. 1.]
[0. 1. 1. 0. 1. 0. 0. 0. 1.]
[0. 1. 1. 0. 1. 0. 0. 1. 0.]
[0. 1. 0. 1. 1. 0. 1. 0. 0.]
[0. 1. 0. 1. 1. 1. 0. 0. 0.]
[0. 1. 0. 1. 0. 0. 0. 0. 2.]
[0. 2. 0. 1. 0. 0. 0. 0. 1.]
[0. 2. 0. 1. 0. 0. 0. 1. 4.]
[0. 1. 0. 1. 2. 0. 0. 0. 0.]
[0. 1. 0. 1. 0. 0. 2. 0. 0.]
[0. 1. 1. 1. 0. 0. 0. 0. 1.]
[0. 1. 1. 1. 0. 0. 0. 1. 0.]
[0. 1. 1. 0. 0. 1. 0. 1. 4.]
[0. 1. 1. 1. 0. 1. 0. 0. 0.]
[0. 1. 1. 1. 0. 0. 1. 0. 0.]
[0. 1. 1. 0. 0. 0. 0. 2. 4.]
[0. 1. 1. 0. 0. 1. 1. 0. 0.]
[0. 1. 1. 1. 1. 0. 0. 0. 0.]
[0. 1. 1. 2. 0. 0. 0. 0. 0.]
[0. 1. 1. 0. 0. 2. 0. 0. 0.]
[0. 1. 1. 0. 0. 0. 0. 1. 1.]
[0. 1. 0. 1. 1

In [84]:
len(indices)

297

In [85]:
def remove_by_indices(list_of_array, indices):
    for index in range(len(list_of_array)):
        list_of_array[index] = np.delete(list_of_array[index], indices, 0)
    return list_of_array

In [86]:
xpru, y1pru, y2pru, y3pru = remove_by_indices([xori, y1ori, y2ori, y3ori], indices)

In [89]:
filename='../datasets/0612-no_mms-141.npz'
np.savez(filename,alloc=xpru,rt_50=y1pru, rt_99=y2pru, rps=y3pru)

### Combine two datasets

In [90]:
one = '../datasets/0611-mms-175.npz'
two = '../datasets/0612-no_mms-141.npz'

npzfile = np.load(one)
x_one, y1_one, y2_one, y3_one = npzfile['alloc'], npzfile['rt_50'], npzfile['rt_99'], npzfile['rps']

npzfile = np.load(two)
x_two, y1_two, y2_two, y3_two = npzfile['alloc'], npzfile['rt_50'], npzfile['rt_99'], npzfile['rps']


In [100]:
display_matched_items(x_one, x_two, y3_one, y3_two)

[0. 1. 0. 0. 1. 1. 1. 0. 0.] [0. 1. 0. 0. 1. 1. 1. 0. 0.]
[nan 1.235 nan nan 3.005 1.47 0.62 nan nan]
[nan 1.405 nan nan 3.4 0.17 0.64 nan nan]

[1. 1. 0. 0. 1. 0. 0. 0. 1.] [1. 1. 0. 0. 1. 0. 0. 0. 1.]
[2.07 1.21 nan nan 2.98 nan nan nan 2.31]
[2.21 1.41 nan nan 3.355 nan nan nan 4.67]

[1. 1. 0. 0. 1. 0. 0. 1. 0.] [1. 1. 0. 0. 1. 0. 0. 1. 0.]
[2.07 1.22 nan nan 2.99 nan nan 0.82 nan]
[2.205 1.38 nan nan 3.39 nan nan 0.71 nan]

[0. 1. 0. 0. 1. 0. 0. 0. 1.] [0. 1. 0. 0. 1. 0. 0. 0. 1.]
[nan 1.21 nan nan 2.955 nan nan nan 2.39]
[nan 1.445 nan nan 3.365 nan nan nan 4.625]

[0. 1. 0. 0. 1. 0. 0. 1. 0.] [0. 1. 0. 0. 1. 0. 0. 1. 0.]
[nan 1.225 nan nan 2.98 nan nan 0.82 nan]
[nan 1.345 nan nan 3.385 nan nan 0.72 nan]

[2. 1. 0. 0. 0. 0. 1. 0. 0.] [2. 1. 0. 0. 0. 0. 1. 0. 0.]
[2.07 1.245 nan nan nan nan 0.63 nan nan]
[2.215 1.395 nan nan nan nan 0.635 nan nan]

[0. 1. 0. 0. 1. 0. 1. 0. 1.] [0. 1. 0. 0. 1. 0. 1. 0. 1.]
[nan 1.225 nan nan 2.975 nan 0.62 nan 0.675]
[nan 1.515 nan nan 3.395 nan 0

In [93]:
match_dict=ndarray_match(x_one, x_two)
match_dict.keys()

dict_keys([33, 53, 54, 60, 65, 76, 80, 82, 88, 89, 95, 102, 106, 115, 119, 140, 155, 172])

In [94]:
indices = [33, 53, 54, 60, 65, 76, 80, 82, 88, 89, 95, 102, 106, 115, 119, 140, 155, 172]
x_one_rm, y1_one_rm, y2_one_rm, y3_one_rm = remove_by_indices([x_one, y1_one, y2_one, y3_one], indices)

In [98]:
len(x_one_rm), len(y1_one_rm)

(157, 157)

In [101]:
x_com = np.append(x_one_rm, x_two, axis=0)
y1_com = np.append(y1_one_rm, y1_two, axis=0)
y2_com = np.append(y2_one_rm, y2_two, axis=0)
y3_com = np.append(y3_one_rm, y3_two, axis=0)

In [102]:
len(x_com)

298

In [103]:
filename='../datasets/0612-comine-298.npz'
np.savez(filename,alloc=x_com,rt_50=y1_com, rt_99=y2_com, rps=y3_com)